// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file/file.proto

package file

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUploadRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerID              string   `protobuf:"bytes,3,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUploadRequest) Reset()         { *m = CreateUploadRequest{} }
func (m *CreateUploadRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUploadRequest) ProtoMessage()    {}
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{0}
}

func (m *CreateUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUploadRequest.Unmarshal(m, b)
}
func (m *CreateUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUploadRequest.Marshal(b, m, deterministic)
}
func (m *CreateUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadRequest.Merge(m, src)
}
func (m *CreateUploadRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUploadRequest.Size(m)
}
func (m *CreateUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadRequest proto.InternalMessageInfo

func (m *CreateUploadRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *CreateUploadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUploadRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *CreateUploadRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateUploadRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type CreateUploadResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUploadResponse) Reset()         { *m = CreateUploadResponse{} }
func (m *CreateUploadResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUploadResponse) ProtoMessage()    {}
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{1}
}

func (m *CreateUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUploadResponse.Unmarshal(m, b)
}
func (m *CreateUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUploadResponse.Marshal(b, m, deterministic)
}
func (m *CreateUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadResponse.Merge(m, src)
}
func (m *CreateUploadResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUploadResponse.Size(m)
}
func (m *CreateUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadResponse proto.InternalMessageInfo

func (m *CreateUploadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateUploadResponse) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type GenerateKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyRequest) Reset()         { *m = GenerateKeyRequest{} }
func (m *GenerateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyRequest) ProtoMessage()    {}
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{2}
}

func (m *GenerateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyRequest.Unmarshal(m, b)
}
func (m *GenerateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyRequest.Marshal(b, m, deterministic)
}
func (m *GenerateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyRequest.Merge(m, src)
}
func (m *GenerateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyRequest.Size(m)
}
func (m *GenerateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyRequest proto.InternalMessageInfo

type KeyResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyResponse) Reset()         { *m = KeyResponse{} }
func (m *KeyResponse) String() string { return proto.CompactTextString(m) }
func (*KeyResponse) ProtoMessage()    {}
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{3}
}

func (m *KeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyResponse.Unmarshal(m, b)
}
func (m *KeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyResponse.Marshal(b, m, deterministic)
}
func (m *KeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResponse.Merge(m, src)
}
func (m *KeyResponse) XXX_Size() int {
	return xxx_messageInfo_KeyResponse.Size(m)
}
func (m *KeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResponse proto.InternalMessageInfo

func (m *KeyResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdateUploadIDRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UploadID             string   `protobuf:"bytes,2,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUploadIDRequest) Reset()         { *m = UpdateUploadIDRequest{} }
func (m *UpdateUploadIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUploadIDRequest) ProtoMessage()    {}
func (*UpdateUploadIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{4}
}

func (m *UpdateUploadIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUploadIDRequest.Unmarshal(m, b)
}
func (m *UpdateUploadIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUploadIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUploadIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUploadIDRequest.Merge(m, src)
}
func (m *UpdateUploadIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUploadIDRequest.Size(m)
}
func (m *UpdateUploadIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUploadIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUploadIDRequest proto.InternalMessageInfo

func (m *UpdateUploadIDRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUploadIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

func (m *UpdateUploadIDRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type UpdateUploadIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUploadIDResponse) Reset()         { *m = UpdateUploadIDResponse{} }
func (m *UpdateUploadIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUploadIDResponse) ProtoMessage()    {}
func (*UpdateUploadIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{5}
}

func (m *UpdateUploadIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUploadIDResponse.Unmarshal(m, b)
}
func (m *UpdateUploadIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUploadIDResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUploadIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUploadIDResponse.Merge(m, src)
}
func (m *UpdateUploadIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUploadIDResponse.Size(m)
}
func (m *UpdateUploadIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUploadIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUploadIDResponse proto.InternalMessageInfo

type GetUploadByIDRequest struct {
	UploadID             string   `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadByIDRequest) Reset()         { *m = GetUploadByIDRequest{} }
func (m *GetUploadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUploadByIDRequest) ProtoMessage()    {}
func (*GetUploadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{6}
}

func (m *GetUploadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadByIDRequest.Unmarshal(m, b)
}
func (m *GetUploadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUploadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadByIDRequest.Merge(m, src)
}
func (m *GetUploadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUploadByIDRequest.Size(m)
}
func (m *GetUploadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadByIDRequest proto.InternalMessageInfo

func (m *GetUploadByIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

type GetUploadByIDResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	UploadID             string   `protobuf:"bytes,3,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadByIDResponse) Reset()         { *m = GetUploadByIDResponse{} }
func (m *GetUploadByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUploadByIDResponse) ProtoMessage()    {}
func (*GetUploadByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{7}
}

func (m *GetUploadByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadByIDResponse.Unmarshal(m, b)
}
func (m *GetUploadByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetUploadByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadByIDResponse.Merge(m, src)
}
func (m *GetUploadByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUploadByIDResponse.Size(m)
}
func (m *GetUploadByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadByIDResponse proto.InternalMessageInfo

func (m *GetUploadByIDResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetUploadByIDResponse) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetUploadByIDResponse) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

func (m *GetUploadByIDResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteUploadByIDRequest struct {
	UploadID             string   `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUploadByIDRequest) Reset()         { *m = DeleteUploadByIDRequest{} }
func (m *DeleteUploadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUploadByIDRequest) ProtoMessage()    {}
func (*DeleteUploadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{8}
}

func (m *DeleteUploadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUploadByIDRequest.Unmarshal(m, b)
}
func (m *DeleteUploadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUploadByIDRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUploadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUploadByIDRequest.Merge(m, src)
}
func (m *DeleteUploadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUploadByIDRequest.Size(m)
}
func (m *DeleteUploadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUploadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUploadByIDRequest proto.InternalMessageInfo

func (m *DeleteUploadByIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

type DeleteUploadByIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUploadByIDResponse) Reset()         { *m = DeleteUploadByIDResponse{} }
func (m *DeleteUploadByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUploadByIDResponse) ProtoMessage()    {}
func (*DeleteUploadByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{9}
}

func (m *DeleteUploadByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUploadByIDResponse.Unmarshal(m, b)
}
func (m *DeleteUploadByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUploadByIDResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUploadByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUploadByIDResponse.Merge(m, src)
}
func (m *DeleteUploadByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUploadByIDResponse.Size(m)
}
func (m *DeleteUploadByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUploadByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUploadByIDResponse proto.InternalMessageInfo

type GetByFileByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByFileByIDRequest) Reset()         { *m = GetByFileByIDRequest{} }
func (m *GetByFileByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByFileByIDRequest) ProtoMessage()    {}
func (*GetByFileByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{10}
}

func (m *GetByFileByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFileByIDRequest.Unmarshal(m, b)
}
func (m *GetByFileByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFileByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByFileByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFileByIDRequest.Merge(m, src)
}
func (m *GetByFileByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByFileByIDRequest.Size(m)
}
func (m *GetByFileByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFileByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFileByIDRequest proto.InternalMessageInfo

func (m *GetByFileByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileByKeyRequest) Reset()         { *m = GetFileByKeyRequest{} }
func (m *GetFileByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileByKeyRequest) ProtoMessage()    {}
func (*GetFileByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{11}
}

func (m *GetFileByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileByKeyRequest.Unmarshal(m, b)
}
func (m *GetFileByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileByKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetFileByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileByKeyRequest.Merge(m, src)
}
func (m *GetFileByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileByKeyRequest.Size(m)
}
func (m *GetFileByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileByKeyRequest proto.InternalMessageInfo

func (m *GetFileByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFilesByFolderRequest struct {
	FolderID             string   `protobuf:"bytes,1,opt,name=folderID,proto3" json:"folderID,omitempty"`
	OwnerID              string   `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	QueryFile            *File    `protobuf:"bytes,3,opt,name=queryFile,proto3" json:"queryFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesByFolderRequest) Reset()         { *m = GetFilesByFolderRequest{} }
func (m *GetFilesByFolderRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilesByFolderRequest) ProtoMessage()    {}
func (*GetFilesByFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{12}
}

func (m *GetFilesByFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesByFolderRequest.Unmarshal(m, b)
}
func (m *GetFilesByFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesByFolderRequest.Marshal(b, m, deterministic)
}
func (m *GetFilesByFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesByFolderRequest.Merge(m, src)
}
func (m *GetFilesByFolderRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilesByFolderRequest.Size(m)
}
func (m *GetFilesByFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesByFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesByFolderRequest proto.InternalMessageInfo

func (m *GetFilesByFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func (m *GetFilesByFolderRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *GetFilesByFolderRequest) GetQueryFile() *File {
	if m != nil {
		return m.QueryFile
	}
	return nil
}

type GetFilesByFolderResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesByFolderResponse) Reset()         { *m = GetFilesByFolderResponse{} }
func (m *GetFilesByFolderResponse) String() string { return proto.CompactTextString(m) }
func (*GetFilesByFolderResponse) ProtoMessage()    {}
func (*GetFilesByFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{13}
}

func (m *GetFilesByFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesByFolderResponse.Unmarshal(m, b)
}
func (m *GetFilesByFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesByFolderResponse.Marshal(b, m, deterministic)
}
func (m *GetFilesByFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesByFolderResponse.Merge(m, src)
}
func (m *GetFilesByFolderResponse) XXX_Size() int {
	return xxx_messageInfo_GetFilesByFolderResponse.Size(m)
}
func (m *GetFilesByFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesByFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesByFolderResponse proto.InternalMessageInfo

func (m *GetFilesByFolderResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetDescendantsByFolderRequest struct {
	FolderID             string   `protobuf:"bytes,1,opt,name=folderID,proto3" json:"folderID,omitempty"`
	OwnerID              string   `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	QueryFile            *File    `protobuf:"bytes,3,opt,name=queryFile,proto3" json:"queryFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDescendantsByFolderRequest) Reset()         { *m = GetDescendantsByFolderRequest{} }
func (m *GetDescendantsByFolderRequest) String() string { return proto.CompactTextString(m) }
func (*GetDescendantsByFolderRequest) ProtoMessage()    {}
func (*GetDescendantsByFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{14}
}

func (m *GetDescendantsByFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDescendantsByFolderRequest.Unmarshal(m, b)
}
func (m *GetDescendantsByFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDescendantsByFolderRequest.Marshal(b, m, deterministic)
}
func (m *GetDescendantsByFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDescendantsByFolderRequest.Merge(m, src)
}
func (m *GetDescendantsByFolderRequest) XXX_Size() int {
	return xxx_messageInfo_GetDescendantsByFolderRequest.Size(m)
}
func (m *GetDescendantsByFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDescendantsByFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDescendantsByFolderRequest proto.InternalMessageInfo

func (m *GetDescendantsByFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func (m *GetDescendantsByFolderRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *GetDescendantsByFolderRequest) GetQueryFile() *File {
	if m != nil {
		return m.QueryFile
	}
	return nil
}

type GetDescendantsByFolderResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDescendantsByFolderResponse) Reset()         { *m = GetDescendantsByFolderResponse{} }
func (m *GetDescendantsByFolderResponse) String() string { return proto.CompactTextString(m) }
func (*GetDescendantsByFolderResponse) ProtoMessage()    {}
func (*GetDescendantsByFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{15}
}

func (m *GetDescendantsByFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDescendantsByFolderResponse.Unmarshal(m, b)
}
func (m *GetDescendantsByFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDescendantsByFolderResponse.Marshal(b, m, deterministic)
}
func (m *GetDescendantsByFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDescendantsByFolderResponse.Merge(m, src)
}
func (m *GetDescendantsByFolderResponse) XXX_Size() int {
	return xxx_messageInfo_GetDescendantsByFolderResponse.Size(m)
}
func (m *GetDescendantsByFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDescendantsByFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDescendantsByFolderResponse proto.InternalMessageInfo

func (m *GetDescendantsByFolderResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type CreateFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	OwnerID              string   `protobuf:"bytes,5,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Bucket               string   `protobuf:"bytes,6,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Parent               string   `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileRequest) Reset()         { *m = CreateFileRequest{} }
func (m *CreateFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileRequest) ProtoMessage()    {}
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{16}
}

func (m *CreateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileRequest.Unmarshal(m, b)
}
func (m *CreateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileRequest.Marshal(b, m, deterministic)
}
func (m *CreateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileRequest.Merge(m, src)
}
func (m *CreateFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileRequest.Size(m)
}
func (m *CreateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileRequest proto.InternalMessageInfo

func (m *CreateFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateFileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFileRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateFileRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateFileRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *CreateFileRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *CreateFileRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type DeleteFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{17}
}

func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(m, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletedFileObject struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletedFileObject) Reset()         { *m = DeletedFileObject{} }
func (m *DeletedFileObject) String() string { return proto.CompactTextString(m) }
func (*DeletedFileObject) ProtoMessage()    {}
func (*DeletedFileObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{18}
}

func (m *DeletedFileObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletedFileObject.Unmarshal(m, b)
}
func (m *DeletedFileObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletedFileObject.Marshal(b, m, deterministic)
}
func (m *DeletedFileObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletedFileObject.Merge(m, src)
}
func (m *DeletedFileObject) XXX_Size() int {
	return xxx_messageInfo_DeletedFileObject.Size(m)
}
func (m *DeletedFileObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletedFileObject.DiscardUnknown(m)
}

var xxx_messageInfo_DeletedFileObject proto.InternalMessageInfo

func (m *DeletedFileObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeletedFileObject) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeletedFileObject) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type DeleteFileResponse struct {
	Files                []*DeletedFileObject `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{19}
}

func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(m, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetFiles() []*DeletedFileObject {
	if m != nil {
		return m.Files
	}
	return nil
}

type IsAllowedRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedRequest) Reset()         { *m = IsAllowedRequest{} }
func (m *IsAllowedRequest) String() string { return proto.CompactTextString(m) }
func (*IsAllowedRequest) ProtoMessage()    {}
func (*IsAllowedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{20}
}

func (m *IsAllowedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedRequest.Unmarshal(m, b)
}
func (m *IsAllowedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedRequest.Marshal(b, m, deterministic)
}
func (m *IsAllowedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedRequest.Merge(m, src)
}
func (m *IsAllowedRequest) XXX_Size() int {
	return xxx_messageInfo_IsAllowedRequest.Size(m)
}
func (m *IsAllowedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedRequest proto.InternalMessageInfo

func (m *IsAllowedRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *IsAllowedRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type IsAllowedResponse struct {
	Allowed              bool     `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedResponse) Reset()         { *m = IsAllowedResponse{} }
func (m *IsAllowedResponse) String() string { return proto.CompactTextString(m) }
func (*IsAllowedResponse) ProtoMessage()    {}
func (*IsAllowedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{21}
}

func (m *IsAllowedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedResponse.Unmarshal(m, b)
}
func (m *IsAllowedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedResponse.Marshal(b, m, deterministic)
}
func (m *IsAllowedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedResponse.Merge(m, src)
}
func (m *IsAllowedResponse) XXX_Size() int {
	return xxx_messageInfo_IsAllowedResponse.Size(m)
}
func (m *IsAllowedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedResponse proto.InternalMessageInfo

func (m *IsAllowedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{22}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

type App struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{23}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type File struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID     string `protobuf:"bytes,6,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Size        int64  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// Types that are valid to be assigned to FileOrId:
	//	*File_Parent
	//	*File_ParentObject
	FileOrId             isFile_FileOrId `protobuf_oneof:"fileOrId"`
	Bucket               string          `protobuf:"bytes,10,opt,name=bucket,proto3" json:"bucket,omitempty"`
	CreatedAt            int64           `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64           `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Children             []*File         `protobuf:"bytes,13,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{24}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *File) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type isFile_FileOrId interface {
	isFile_FileOrId()
}

type File_Parent struct {
	Parent string `protobuf:"bytes,8,opt,name=parent,proto3,oneof"`
}

type File_ParentObject struct {
	ParentObject *File `protobuf:"bytes,9,opt,name=parentObject,proto3,oneof"`
}

func (*File_Parent) isFile_FileOrId() {}

func (*File_ParentObject) isFile_FileOrId() {}

func (m *File) GetFileOrId() isFile_FileOrId {
	if m != nil {
		return m.FileOrId
	}
	return nil
}

func (m *File) GetParent() string {
	if x, ok := m.GetFileOrId().(*File_Parent); ok {
		return x.Parent
	}
	return ""
}

func (m *File) GetParentObject() *File {
	if x, ok := m.GetFileOrId().(*File_ParentObject); ok {
		return x.ParentObject
	}
	return nil
}

func (m *File) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *File) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *File) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *File) GetChildren() []*File {
	if m != nil {
		return m.Children
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*File) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*File_Parent)(nil),
		(*File_ParentObject)(nil),
	}
}

type UpdateFilesRequest struct {
	IdList               []string `protobuf:"bytes,1,rep,name=idList,proto3" json:"idList,omitempty"`
	PartialFile          *File    `protobuf:"bytes,2,opt,name=partialFile,proto3" json:"partialFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFilesRequest) Reset()         { *m = UpdateFilesRequest{} }
func (m *UpdateFilesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFilesRequest) ProtoMessage()    {}
func (*UpdateFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{25}
}

func (m *UpdateFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFilesRequest.Unmarshal(m, b)
}
func (m *UpdateFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFilesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFilesRequest.Merge(m, src)
}
func (m *UpdateFilesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFilesRequest.Size(m)
}
func (m *UpdateFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFilesRequest proto.InternalMessageInfo

func (m *UpdateFilesRequest) GetIdList() []string {
	if m != nil {
		return m.IdList
	}
	return nil
}

func (m *UpdateFilesRequest) GetPartialFile() *File {
	if m != nil {
		return m.PartialFile
	}
	return nil
}

type UpdateFilesResponse struct {
	FailedFiles          []*FailedFile `protobuf:"bytes,1,rep,name=failedFiles,proto3" json:"failedFiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateFilesResponse) Reset()         { *m = UpdateFilesResponse{} }
func (m *UpdateFilesResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateFilesResponse) ProtoMessage()    {}
func (*UpdateFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{26}
}

func (m *UpdateFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFilesResponse.Unmarshal(m, b)
}
func (m *UpdateFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFilesResponse.Marshal(b, m, deterministic)
}
func (m *UpdateFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFilesResponse.Merge(m, src)
}
func (m *UpdateFilesResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateFilesResponse.Size(m)
}
func (m *UpdateFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFilesResponse proto.InternalMessageInfo

func (m *UpdateFilesResponse) GetFailedFiles() []*FailedFile {
	if m != nil {
		return m.FailedFiles
	}
	return nil
}

type FailedFile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailedFile) Reset()         { *m = FailedFile{} }
func (m *FailedFile) String() string { return proto.CompactTextString(m) }
func (*FailedFile) ProtoMessage()    {}
func (*FailedFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{27}
}

func (m *FailedFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailedFile.Unmarshal(m, b)
}
func (m *FailedFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailedFile.Marshal(b, m, deterministic)
}
func (m *FailedFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailedFile.Merge(m, src)
}
func (m *FailedFile) XXX_Size() int {
	return xxx_messageInfo_FailedFile.Size(m)
}
func (m *FailedFile) XXX_DiscardUnknown() {
	xxx_messageInfo_FailedFile.DiscardUnknown(m)
}

var xxx_messageInfo_FailedFile proto.InternalMessageInfo

func (m *FailedFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FailedFile) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetAncestorsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAncestorsRequest) Reset()         { *m = GetAncestorsRequest{} }
func (m *GetAncestorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsRequest) ProtoMessage()    {}
func (*GetAncestorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{28}
}

func (m *GetAncestorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsRequest.Unmarshal(m, b)
}
func (m *GetAncestorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsRequest.Marshal(b, m, deterministic)
}
func (m *GetAncestorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsRequest.Merge(m, src)
}
func (m *GetAncestorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsRequest.Size(m)
}
func (m *GetAncestorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsRequest proto.InternalMessageInfo

func (m *GetAncestorsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAncestorsResponse struct {
	Ancestors            []string `protobuf:"bytes,1,rep,name=ancestors,proto3" json:"ancestors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAncestorsResponse) Reset()         { *m = GetAncestorsResponse{} }
func (m *GetAncestorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAncestorsResponse) ProtoMessage()    {}
func (*GetAncestorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{29}
}

func (m *GetAncestorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAncestorsResponse.Unmarshal(m, b)
}
func (m *GetAncestorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAncestorsResponse.Marshal(b, m, deterministic)
}
func (m *GetAncestorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAncestorsResponse.Merge(m, src)
}
func (m *GetAncestorsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAncestorsResponse.Size(m)
}
func (m *GetAncestorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAncestorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAncestorsResponse proto.InternalMessageInfo

func (m *GetAncestorsResponse) GetAncestors() []string {
	if m != nil {
		return m.Ancestors
	}
	return nil
}

type SetFileFloatRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsFloat              bool     `protobuf:"varint,2,opt,name=isFloat,proto3" json:"isFloat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetFileFloatRequest) Reset()         { *m = SetFileFloatRequest{} }
func (m *SetFileFloatRequest) String() string { return proto.CompactTextString(m) }
func (*SetFileFloatRequest) ProtoMessage()    {}
func (*SetFileFloatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{30}
}

func (m *SetFileFloatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetFileFloatRequest.Unmarshal(m, b)
}
func (m *SetFileFloatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetFileFloatRequest.Marshal(b, m, deterministic)
}
func (m *SetFileFloatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetFileFloatRequest.Merge(m, src)
}
func (m *SetFileFloatRequest) XXX_Size() int {
	return xxx_messageInfo_SetFileFloatRequest.Size(m)
}
func (m *SetFileFloatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetFileFloatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetFileFloatRequest proto.InternalMessageInfo

func (m *SetFileFloatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetFileFloatRequest) GetIsFloat() bool {
	if m != nil {
		return m.IsFloat
	}
	return false
}

type SetFileFloatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetFileFloatResponse) Reset()         { *m = SetFileFloatResponse{} }
func (m *SetFileFloatResponse) String() string { return proto.CompactTextString(m) }
func (*SetFileFloatResponse) ProtoMessage()    {}
func (*SetFileFloatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad806f8986a0c3f6, []int{31}
}

func (m *SetFileFloatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetFileFloatResponse.Unmarshal(m, b)
}
func (m *SetFileFloatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetFileFloatResponse.Marshal(b, m, deterministic)
}
func (m *SetFileFloatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetFileFloatResponse.Merge(m, src)
}
func (m *SetFileFloatResponse) XXX_Size() int {
	return xxx_messageInfo_SetFileFloatResponse.Size(m)
}
func (m *SetFileFloatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetFileFloatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetFileFloatResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateUploadRequest)(nil), "file.CreateUploadRequest")
	proto.RegisterType((*CreateUploadResponse)(nil), "file.CreateUploadResponse")
	proto.RegisterType((*GenerateKeyRequest)(nil), "file.GenerateKeyRequest")
	proto.RegisterType((*KeyResponse)(nil), "file.KeyResponse")
	proto.RegisterType((*UpdateUploadIDRequest)(nil), "file.UpdateUploadIDRequest")
	proto.RegisterType((*UpdateUploadIDResponse)(nil), "file.UpdateUploadIDResponse")
	proto.RegisterType((*GetUploadByIDRequest)(nil), "file.GetUploadByIDRequest")
	proto.RegisterType((*GetUploadByIDResponse)(nil), "file.GetUploadByIDResponse")
	proto.RegisterType((*DeleteUploadByIDRequest)(nil), "file.DeleteUploadByIDRequest")
	proto.RegisterType((*DeleteUploadByIDResponse)(nil), "file.DeleteUploadByIDResponse")
	proto.RegisterType((*GetByFileByIDRequest)(nil), "file.GetByFileByIDRequest")
	proto.RegisterType((*GetFileByKeyRequest)(nil), "file.GetFileByKeyRequest")
	proto.RegisterType((*GetFilesByFolderRequest)(nil), "file.GetFilesByFolderRequest")
	proto.RegisterType((*GetFilesByFolderResponse)(nil), "file.GetFilesByFolderResponse")
	proto.RegisterType((*GetDescendantsByFolderRequest)(nil), "file.GetDescendantsByFolderRequest")
	proto.RegisterType((*GetDescendantsByFolderResponse)(nil), "file.GetDescendantsByFolderResponse")
	proto.RegisterType((*CreateFileRequest)(nil), "file.CreateFileRequest")
	proto.RegisterType((*DeleteFileRequest)(nil), "file.DeleteFileRequest")
	proto.RegisterType((*DeletedFileObject)(nil), "file.DeletedFileObject")
	proto.RegisterType((*DeleteFileResponse)(nil), "file.DeleteFileResponse")
	proto.RegisterType((*IsAllowedRequest)(nil), "file.IsAllowedRequest")
	proto.RegisterType((*IsAllowedResponse)(nil), "file.IsAllowedResponse")
	proto.RegisterType((*User)(nil), "file.User")
	proto.RegisterType((*App)(nil), "file.App")
	proto.RegisterType((*File)(nil), "file.File")
	proto.RegisterType((*UpdateFilesRequest)(nil), "file.UpdateFilesRequest")
	proto.RegisterType((*UpdateFilesResponse)(nil), "file.UpdateFilesResponse")
	proto.RegisterType((*FailedFile)(nil), "file.FailedFile")
	proto.RegisterType((*GetAncestorsRequest)(nil), "file.GetAncestorsRequest")
	proto.RegisterType((*GetAncestorsResponse)(nil), "file.GetAncestorsResponse")
	proto.RegisterType((*SetFileFloatRequest)(nil), "file.SetFileFloatRequest")
	proto.RegisterType((*SetFileFloatResponse)(nil), "file.SetFileFloatResponse")
}

func init() { proto.RegisterFile("file/file.proto", fileDescriptor_ad806f8986a0c3f6) }

var fileDescriptor_ad806f8986a0c3f6 = []byte{
	// 1115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0x4f, 0x9c, 0xb4, 0x4d, 0x4e, 0xba, 0x91, 0xde, 0x66, 0x89, 0xe7, 0x75, 0x23, 0xba, 0x83,
	0x51, 0x24, 0x36, 0x50, 0x06, 0xe2, 0x65, 0x02, 0x12, 0xa2, 0x66, 0x19, 0x8c, 0x49, 0xa9, 0xfa,
	0x82, 0xc4, 0x83, 0x1b, 0xdf, 0x0a, 0x33, 0xcf, 0x76, 0x6d, 0x87, 0x2a, 0xbc, 0xf0, 0xc8, 0x87,
	0xe1, 0x5b, 0xf0, 0x99, 0xf8, 0x00, 0xe8, 0xfe, 0xb3, 0x8f, 0x7d, 0x1d, 0x54, 0x5e, 0x78, 0x89,
	0x7c, 0xfe, 0xdc, 0xf3, 0xef, 0xfe, 0xee, 0x39, 0x27, 0xf0, 0xde, 0x95, 0x1f, 0xb0, 0x4f, 0xf9,
	0xcf, 0xb3, 0x38, 0x89, 0xb2, 0x88, 0xb4, 0xf9, 0x37, 0xfd, 0xa3, 0x09, 0xc7, 0xdf, 0x26, 0xcc,
	0xcd, 0xd8, 0x45, 0x1c, 0x44, 0xae, 0xb7, 0x62, 0xd7, 0x1b, 0x96, 0x66, 0x64, 0x08, 0xfb, 0x97,
	0x9b, 0xf5, 0x5b, 0x96, 0xd9, 0xcd, 0x71, 0xf3, 0xb4, 0xbb, 0x52, 0x14, 0x21, 0xd0, 0x0e, 0xdd,
	0x77, 0xcc, 0xb6, 0x04, 0x57, 0x7c, 0x13, 0x1b, 0x0e, 0xa2, 0x9b, 0x90, 0x25, 0xcb, 0xb9, 0xdd,
	0x12, 0x6c, 0x4d, 0x72, 0x2b, 0xb1, 0x9b, 0xb0, 0x30, 0xb3, 0xdb, 0xd2, 0x8a, 0xa4, 0xb8, 0x95,
	0xd4, 0xff, 0x8d, 0xd9, 0x7b, 0xe3, 0xe6, 0x69, 0x6b, 0x25, 0xbe, 0xe9, 0x37, 0x30, 0x28, 0x07,
	0x92, 0xc6, 0x51, 0x98, 0x32, 0xd2, 0x87, 0xd6, 0x5b, 0xb6, 0x55, 0x61, 0xf0, 0x4f, 0x14, 0x9b,
	0x85, 0x63, 0xa3, 0x03, 0x20, 0x0b, 0x16, 0xb2, 0xc4, 0xcd, 0xd8, 0x77, 0x6c, 0xab, 0x32, 0xa1,
	0xef, 0x43, 0x4f, 0x50, 0xbb, 0xcc, 0xd1, 0x9f, 0xe0, 0xde, 0x45, 0xec, 0xe5, 0x8e, 0x97, 0x73,
	0x5d, 0x03, 0xd3, 0xb3, 0x03, 0x9d, 0x8d, 0x52, 0x52, 0xbe, 0x73, 0x1a, 0x45, 0xd5, 0x2a, 0x45,
	0x65, 0xc3, 0xb0, 0x6a, 0x5e, 0x86, 0x42, 0x27, 0x30, 0x58, 0xb0, 0x4c, 0xb2, 0x67, 0xdb, 0xc2,
	0x2f, 0xf6, 0xd2, 0x2c, 0x7b, 0xa1, 0xd7, 0x70, 0xaf, 0x72, 0xe6, 0xbf, 0x96, 0xa9, 0x64, 0xbe,
	0x55, 0x49, 0x42, 0x5f, 0x6f, 0xbb, 0xb8, 0x5e, 0xfa, 0x05, 0x8c, 0xe6, 0x2c, 0x60, 0x3a, 0x81,
	0xdb, 0x46, 0xea, 0x80, 0x6d, 0x1e, 0x53, 0x99, 0x3f, 0x11, 0x99, 0xcf, 0xb6, 0x67, 0x7e, 0xc0,
	0xb0, 0xbd, 0xbb, 0x60, 0xf9, 0x9e, 0xb2, 0x64, 0xf9, 0x1e, 0xfd, 0x08, 0x8e, 0x17, 0x2c, 0x93,
	0x5a, 0xc5, 0x95, 0xd6, 0xdc, 0xe1, 0x16, 0x46, 0x4a, 0x31, 0x9d, 0x6d, 0xcf, 0xa2, 0xc0, 0x63,
	0x09, 0x8a, 0xf1, 0x4a, 0x30, 0x8a, 0x18, 0x35, 0x8d, 0x91, 0x6b, 0x95, 0x91, 0x7b, 0x0a, 0xdd,
	0xeb, 0x0d, 0x4b, 0x44, 0x84, 0xa2, 0x4a, 0xbd, 0x09, 0x3c, 0x13, 0xaf, 0x87, 0x73, 0x56, 0x85,
	0x90, 0xbe, 0x00, 0xdb, 0x74, 0xad, 0x2e, 0x65, 0x0c, 0x7b, 0xfc, 0x4c, 0x6a, 0x37, 0xc7, 0xad,
	0x8a, 0x05, 0x29, 0xa0, 0xbf, 0xc3, 0xc3, 0x05, 0xcb, 0xe6, 0x2c, 0x5d, 0xb3, 0xd0, 0x73, 0xc3,
	0xec, 0x7f, 0x0f, 0x7f, 0x06, 0x8f, 0x76, 0x05, 0x70, 0xeb, 0x24, 0xfe, 0x6c, 0xc2, 0x91, 0x7c,
	0xbb, 0x82, 0xbb, 0xf3, 0xf9, 0xd4, 0x35, 0x0f, 0xdd, 0x0a, 0x5a, 0x45, 0x2b, 0xe0, 0xbc, 0x6c,
	0x1b, 0xe7, 0x28, 0xe4, 0xdf, 0x38, 0xd7, 0x3d, 0xa3, 0xc9, 0x28, 0x9c, 0xef, 0x97, 0x70, 0x5e,
	0x34, 0x9f, 0x03, 0xdc, 0x7c, 0xe8, 0x63, 0x38, 0x92, 0xc0, 0xc4, 0xc1, 0x56, 0x91, 0xf7, 0x5a,
	0x2b, 0x79, 0x5c, 0xeb, 0xcd, 0xe5, 0x2f, 0x6c, 0x6d, 0x28, 0xe9, 0x0c, 0xad, 0xba, 0x37, 0x57,
	0x6e, 0x02, 0x4b, 0x20, 0xd8, 0xa7, 0xaa, 0xec, 0x53, 0x5d, 0x59, 0x4b, 0x54, 0x76, 0x24, 0x2b,
	0x6b, 0xf8, 0x55, 0x65, 0x7e, 0xd5, 0xee, 0x34, 0xfb, 0x16, 0x9d, 0x41, 0x7f, 0x99, 0x4e, 0x83,
	0x20, 0xba, 0x61, 0xb8, 0x5b, 0x73, 0x95, 0x1c, 0x22, 0x8a, 0xe2, 0xfc, 0x4d, 0x8a, 0xf0, 0xa1,
	0x28, 0xfa, 0x14, 0x8e, 0x90, 0x0d, 0x15, 0x8d, 0x0d, 0x07, 0xae, 0x64, 0x09, 0x2b, 0x9d, 0x95,
	0x26, 0xa9, 0x07, 0xed, 0x8b, 0x94, 0x25, 0x46, 0xfe, 0x27, 0xd0, 0xbd, 0xf2, 0x93, 0x34, 0xfb,
	0xa1, 0xb8, 0xd4, 0x82, 0xc1, 0x91, 0x1b, 0xb8, 0x4a, 0xa8, 0xfa, 0x8c, 0xa6, 0xf9, 0x0d, 0xbf,
	0x73, 0xfd, 0x40, 0xdf, 0x30, 0xff, 0xa6, 0x1f, 0x43, 0x6b, 0x1a, 0xc7, 0x86, 0x93, 0x1a, 0xd0,
	0xd0, 0xbf, 0x2d, 0x68, 0xf3, 0xfa, 0xdc, 0xe2, 0x46, 0xf4, 0xf1, 0x56, 0x19, 0x73, 0x06, 0xbe,
	0xc6, 0xd0, 0xf3, 0x58, 0xba, 0x4e, 0xfc, 0x38, 0xf3, 0xa3, 0x50, 0x61, 0x0c, 0xb3, 0x30, 0x02,
	0xf7, 0xcb, 0x08, 0xd4, 0x18, 0x3e, 0x40, 0x18, 0xb6, 0x73, 0xf4, 0x75, 0xb8, 0xf2, 0xcb, 0x46,
	0x3e, 0xfc, 0x3e, 0x83, 0x43, 0xf9, 0x25, 0x6f, 0xd7, 0xee, 0x56, 0x9f, 0xe7, 0xcb, 0xc6, 0xaa,
	0xa4, 0x81, 0x50, 0x05, 0x25, 0x84, 0x9f, 0x40, 0x77, 0x2d, 0x9e, 0x9d, 0x37, 0xcd, 0xec, 0x9e,
	0x70, 0x5e, 0x30, 0xb8, 0x74, 0x23, 0x06, 0x0f, 0x97, 0x1e, 0x4a, 0x69, 0xce, 0x20, 0x4f, 0xa0,
	0xb3, 0xfe, 0xd9, 0x0f, 0xbc, 0x84, 0x85, 0xf6, 0x1d, 0xe3, 0x61, 0xe7, 0xb2, 0x19, 0x40, 0x87,
	0xb3, 0xdf, 0x24, 0x4b, 0x8f, 0xfe, 0x08, 0x44, 0x8e, 0x32, 0xd1, 0xed, 0x10, 0xf8, 0x7c, 0xef,
	0x7b, 0x3f, 0xcd, 0x44, 0x83, 0xe8, 0xae, 0x14, 0x45, 0x3e, 0x81, 0x5e, 0xec, 0x26, 0x99, 0xef,
	0x06, 0xa2, 0x0b, 0x59, 0x46, 0x17, 0xc2, 0x62, 0xba, 0x84, 0xe3, 0x92, 0x6d, 0x05, 0xca, 0x09,
	0xf4, 0xae, 0x5c, 0x3f, 0x90, 0xcf, 0x41, 0xb7, 0xa0, 0xbe, 0x32, 0x92, 0x0b, 0x56, 0x58, 0x89,
	0x4e, 0x00, 0x0a, 0x91, 0x01, 0x91, 0x01, 0xec, 0xb1, 0x24, 0x89, 0x12, 0x05, 0x12, 0x49, 0xd0,
	0x0f, 0xc5, 0xa4, 0x99, 0x86, 0x6b, 0x96, 0x66, 0x51, 0x92, 0xee, 0x6a, 0x0b, 0x9f, 0x8b, 0xc1,
	0x85, 0xd4, 0x54, 0x98, 0x27, 0xd0, 0x75, 0x35, 0x53, 0x95, 0xa1, 0x60, 0xd0, 0xaf, 0xe1, 0xf8,
	0x5c, 0x8e, 0x88, 0xb3, 0x20, 0x72, 0xb3, 0x1d, 0xc6, 0x39, 0xc0, 0xfc, 0x54, 0x68, 0x88, 0xd8,
	0x3a, 0x2b, 0x4d, 0xd2, 0x21, 0x0c, 0xca, 0x06, 0xa4, 0xdb, 0xc9, 0x5f, 0x1d, 0xe8, 0x71, 0xee,
	0x39, 0x4b, 0x7e, 0xf5, 0xd7, 0x8c, 0xbc, 0x80, 0x1e, 0xda, 0x80, 0x88, 0x2d, 0xeb, 0x64, 0x2e,
	0x45, 0xce, 0x91, 0x94, 0xa0, 0xc5, 0x88, 0x36, 0xc8, 0x02, 0x0e, 0xf1, 0x06, 0x46, 0xee, 0x4b,
	0xa5, 0x9a, 0xf5, 0xd0, 0x71, 0xea, 0x44, 0xb9, 0xa1, 0xd7, 0x70, 0xb7, 0xbc, 0xf2, 0x90, 0x07,
	0x52, 0xbf, 0x76, 0xcf, 0x72, 0x4e, 0xea, 0x85, 0xb9, 0xb9, 0x57, 0x70, 0xa7, 0xb4, 0xf3, 0x10,
	0x47, 0xe7, 0x65, 0x2e, 0x4f, 0xce, 0x83, 0x5a, 0x59, 0x6e, 0xeb, 0x1c, 0xfa, 0xd5, 0xad, 0x84,
	0x3c, 0xc4, 0x7d, 0xd7, 0xb4, 0xf8, 0x68, 0x97, 0x38, 0x37, 0xfa, 0x25, 0x2f, 0x7b, 0xa6, 0x97,
	0x19, 0x14, 0x9e, 0xb1, 0xe1, 0x38, 0x08, 0xff, 0xe2, 0xe0, 0x21, 0xde, 0x6f, 0x74, 0xc5, 0x6b,
	0x76, 0x9e, 0xca, 0xc1, 0x73, 0xe8, 0x57, 0x97, 0x0e, 0x9d, 0xc6, 0x8e, 0x3d, 0x48, 0xa7, 0xb1,
	0x6b, 0x57, 0xa1, 0x0d, 0xc2, 0x60, 0x58, 0xbf, 0x0a, 0x90, 0xc7, 0xf9, 0xd9, 0xdd, 0x9b, 0x8a,
	0xf3, 0xc1, 0xbf, 0x2b, 0xe5, 0x6e, 0x9e, 0x03, 0x14, 0xcb, 0x02, 0x19, 0x61, 0x24, 0xa1, 0x89,
	0x5c, 0x49, 0x78, 0x0a, 0x50, 0x0c, 0x50, 0x52, 0x9a, 0x94, 0xf8, 0x90, 0x6d, 0x0a, 0x72, 0xbf,
	0x5f, 0x41, 0x37, 0x1f, 0x7a, 0x64, 0x28, 0x15, 0xab, 0x93, 0xd4, 0x19, 0x19, 0xfc, 0xfc, 0xfc,
	0x1c, 0x7a, 0xa8, 0x43, 0xe9, 0xc7, 0x65, 0x36, 0x44, 0xe7, 0x7e, 0x8d, 0x04, 0x3f, 0x32, 0xdc,
	0x41, 0xd0, 0x95, 0x57, 0x9b, 0x8f, 0xe3, 0xd4, 0x89, 0xb0, 0x21, 0xdc, 0x13, 0xb4, 0xa1, 0x9a,
	0x46, 0xa3, 0x0d, 0xd5, 0xb5, 0x10, 0xda, 0xb8, 0xdc, 0x17, 0xff, 0x07, 0x9f, 0xff, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xd1, 0x4b, 0xb9, 0x90, 0x22, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileServiceClient interface {
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error)
	CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error)
	UpdateUploadID(ctx context.Context, in *UpdateUploadIDRequest, opts ...grpc.CallOption) (*UpdateUploadIDResponse, error)
	GetUploadByID(ctx context.Context, in *GetUploadByIDRequest, opts ...grpc.CallOption) (*GetUploadByIDResponse, error)
	DeleteUploadByID(ctx context.Context, in *DeleteUploadByIDRequest, opts ...grpc.CallOption) (*DeleteUploadByIDResponse, error)
	GetFileByID(ctx context.Context, in *GetByFileByIDRequest, opts ...grpc.CallOption) (*File, error)
	GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (*File, error)
	GetFilesByFolder(ctx context.Context, in *GetFilesByFolderRequest, opts ...grpc.CallOption) (*GetFilesByFolderResponse, error)
	GetDescendantsByFolder(ctx context.Context, in *GetDescendantsByFolderRequest, opts ...grpc.CallOption) (*GetDescendantsByFolderResponse, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*File, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error)
	UpdateFiles(ctx context.Context, in *UpdateFilesRequest, opts ...grpc.CallOption) (*UpdateFilesResponse, error)
	GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*GetAncestorsResponse, error)
	SetFileFloat(ctx context.Context, in *SetFileFloatRequest, opts ...grpc.CallOption) (*SetFileFloatResponse, error)
}

type fileServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileServiceClient(cc *grpc.ClientConn) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error) {
	out := new(CreateUploadResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/CreateUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateUploadID(ctx context.Context, in *UpdateUploadIDRequest, opts ...grpc.CallOption) (*UpdateUploadIDResponse, error) {
	out := new(UpdateUploadIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/UpdateUploadID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetUploadByID(ctx context.Context, in *GetUploadByIDRequest, opts ...grpc.CallOption) (*GetUploadByIDResponse, error) {
	out := new(GetUploadByIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetUploadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteUploadByID(ctx context.Context, in *DeleteUploadByIDRequest, opts ...grpc.CallOption) (*DeleteUploadByIDResponse, error) {
	out := new(DeleteUploadByIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/DeleteUploadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileByID(ctx context.Context, in *GetByFileByIDRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFileByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFileByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFilesByFolder(ctx context.Context, in *GetFilesByFolderRequest, opts ...grpc.CallOption) (*GetFilesByFolderResponse, error) {
	out := new(GetFilesByFolderResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFilesByFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetDescendantsByFolder(ctx context.Context, in *GetDescendantsByFolderRequest, opts ...grpc.CallOption) (*GetDescendantsByFolderResponse, error) {
	out := new(GetDescendantsByFolderResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetDescendantsByFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/CreateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error) {
	out := new(IsAllowedResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/IsAllowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateFiles(ctx context.Context, in *UpdateFilesRequest, opts ...grpc.CallOption) (*UpdateFilesResponse, error) {
	out := new(UpdateFilesResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/UpdateFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetAncestors(ctx context.Context, in *GetAncestorsRequest, opts ...grpc.CallOption) (*GetAncestorsResponse, error) {
	out := new(GetAncestorsResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetAncestors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) SetFileFloat(ctx context.Context, in *SetFileFloatRequest, opts ...grpc.CallOption) (*SetFileFloatResponse, error) {
	out := new(SetFileFloatResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/SetFileFloat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
type FileServiceServer interface {
	GenerateKey(context.Context, *GenerateKeyRequest) (*KeyResponse, error)
	CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error)
	UpdateUploadID(context.Context, *UpdateUploadIDRequest) (*UpdateUploadIDResponse, error)
	GetUploadByID(context.Context, *GetUploadByIDRequest) (*GetUploadByIDResponse, error)
	DeleteUploadByID(context.Context, *DeleteUploadByIDRequest) (*DeleteUploadByIDResponse, error)
	GetFileByID(context.Context, *GetByFileByIDRequest) (*File, error)
	GetFileByKey(context.Context, *GetFileByKeyRequest) (*File, error)
	GetFilesByFolder(context.Context, *GetFilesByFolderRequest) (*GetFilesByFolderResponse, error)
	GetDescendantsByFolder(context.Context, *GetDescendantsByFolderRequest) (*GetDescendantsByFolderResponse, error)
	CreateFile(context.Context, *CreateFileRequest) (*File, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	IsAllowed(context.Context, *IsAllowedRequest) (*IsAllowedResponse, error)
	UpdateFiles(context.Context, *UpdateFilesRequest) (*UpdateFilesResponse, error)
	GetAncestors(context.Context, *GetAncestorsRequest) (*GetAncestorsResponse, error)
	SetFileFloat(context.Context, *SetFileFloatRequest) (*SetFileFloatResponse, error)
}

// UnimplementedFileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (*UnimplementedFileServiceServer) GenerateKey(ctx context.Context, req *GenerateKeyRequest) (*KeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}
func (*UnimplementedFileServiceServer) CreateUpload(ctx context.Context, req *CreateUploadRequest) (*CreateUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUpload not implemented")
}
func (*UnimplementedFileServiceServer) UpdateUploadID(ctx context.Context, req *UpdateUploadIDRequest) (*UpdateUploadIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUploadID not implemented")
}
func (*UnimplementedFileServiceServer) GetUploadByID(ctx context.Context, req *GetUploadByIDRequest) (*GetUploadByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadByID not implemented")
}
func (*UnimplementedFileServiceServer) DeleteUploadByID(ctx context.Context, req *DeleteUploadByIDRequest) (*DeleteUploadByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUploadByID not implemented")
}
func (*UnimplementedFileServiceServer) GetFileByID(ctx context.Context, req *GetByFileByIDRequest) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileByID not implemented")
}
func (*UnimplementedFileServiceServer) GetFileByKey(ctx context.Context, req *GetFileByKeyRequest) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileByKey not implemented")
}
func (*UnimplementedFileServiceServer) GetFilesByFolder(ctx context.Context, req *GetFilesByFolderRequest) (*GetFilesByFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesByFolder not implemented")
}
func (*UnimplementedFileServiceServer) GetDescendantsByFolder(ctx context.Context, req *GetDescendantsByFolderRequest) (*GetDescendantsByFolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDescendantsByFolder not implemented")
}
func (*UnimplementedFileServiceServer) CreateFile(ctx context.Context, req *CreateFileRequest) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFile not implemented")
}
func (*UnimplementedFileServiceServer) DeleteFile(ctx context.Context, req *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (*UnimplementedFileServiceServer) IsAllowed(ctx context.Context, req *IsAllowedRequest) (*IsAllowedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAllowed not implemented")
}
func (*UnimplementedFileServiceServer) UpdateFiles(ctx context.Context, req *UpdateFilesRequest) (*UpdateFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFiles not implemented")
}
func (*UnimplementedFileServiceServer) GetAncestors(ctx context.Context, req *GetAncestorsRequest) (*GetAncestorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAncestors not implemented")
}
func (*UnimplementedFileServiceServer) SetFileFloat(ctx context.Context, req *SetFileFloatRequest) (*SetFileFloatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFileFloat not implemented")
}

func RegisterFileServiceServer(s *grpc.Server, srv FileServiceServer) {
	s.RegisterService(&_FileService_serviceDesc, srv)
}

func _FileService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/CreateUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateUpload(ctx, req.(*CreateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateUploadID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUploadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateUploadID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/UpdateUploadID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateUploadID(ctx, req.(*UpdateUploadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetUploadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetUploadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetUploadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetUploadByID(ctx, req.(*GetUploadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteUploadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUploadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteUploadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/DeleteUploadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteUploadByID(ctx, req.(*DeleteUploadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByFileByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFileByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileByID(ctx, req.(*GetByFileByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFileByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileByKey(ctx, req.(*GetFileByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFilesByFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFilesByFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFilesByFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFilesByFolder(ctx, req.(*GetFilesByFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetDescendantsByFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDescendantsByFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetDescendantsByFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetDescendantsByFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetDescendantsByFolder(ctx, req.(*GetDescendantsByFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/CreateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_IsAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).IsAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/IsAllowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).IsAllowed(ctx, req.(*IsAllowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/UpdateFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateFiles(ctx, req.(*UpdateFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetAncestors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetAncestors(ctx, req.(*GetAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_SetFileFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFileFloatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).SetFileFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/SetFileFloat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).SetFileFloat(ctx, req.(*SetFileFloatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "file.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _FileService_GenerateKey_Handler,
		},
		{
			MethodName: "CreateUpload",
			Handler:    _FileService_CreateUpload_Handler,
		},
		{
			MethodName: "UpdateUploadID",
			Handler:    _FileService_UpdateUploadID_Handler,
		},
		{
			MethodName: "GetUploadByID",
			Handler:    _FileService_GetUploadByID_Handler,
		},
		{
			MethodName: "DeleteUploadByID",
			Handler:    _FileService_DeleteUploadByID_Handler,
		},
		{
			MethodName: "GetFileByID",
			Handler:    _FileService_GetFileByID_Handler,
		},
		{
			MethodName: "GetFileByKey",
			Handler:    _FileService_GetFileByKey_Handler,
		},
		{
			MethodName: "GetFilesByFolder",
			Handler:    _FileService_GetFilesByFolder_Handler,
		},
		{
			MethodName: "GetDescendantsByFolder",
			Handler:    _FileService_GetDescendantsByFolder_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _FileService_CreateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
		{
			MethodName: "IsAllowed",
			Handler:    _FileService_IsAllowed_Handler,
		},
		{
			MethodName: "UpdateFiles",
			Handler:    _FileService_UpdateFiles_Handler,
		},
		{
			MethodName: "GetAncestors",
			Handler:    _FileService_GetAncestors_Handler,
		},
		{
			MethodName: "SetFileFloat",
			Handler:    _FileService_SetFileFloat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file/file.proto",
}
