// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.8
// source: quota/quota.proto

package quota

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsAllowedToGetQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestingUser string `protobuf:"bytes,1,opt,name=requestingUser,proto3" json:"requestingUser,omitempty"`
	OwnerID        string `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
}

func (x *IsAllowedToGetQuotaRequest) Reset() {
	*x = IsAllowedToGetQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAllowedToGetQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedToGetQuotaRequest) ProtoMessage() {}

func (x *IsAllowedToGetQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedToGetQuotaRequest.ProtoReflect.Descriptor instead.
func (*IsAllowedToGetQuotaRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{0}
}

func (x *IsAllowedToGetQuotaRequest) GetRequestingUser() string {
	if x != nil {
		return x.RequestingUser
	}
	return ""
}

func (x *IsAllowedToGetQuotaRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type IsAllowedToGetQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
}

func (x *IsAllowedToGetQuotaResponse) Reset() {
	*x = IsAllowedToGetQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAllowedToGetQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAllowedToGetQuotaResponse) ProtoMessage() {}

func (x *IsAllowedToGetQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAllowedToGetQuotaResponse.ProtoReflect.Descriptor instead.
func (*IsAllowedToGetQuotaResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{1}
}

func (x *IsAllowedToGetQuotaResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type GetOwnerQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
}

func (x *GetOwnerQuotaRequest) Reset() {
	*x = GetOwnerQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnerQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerQuotaRequest) ProtoMessage() {}

func (x *GetOwnerQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetOwnerQuotaRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{2}
}

func (x *GetOwnerQuotaRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type GetOwnerQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Limit   int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Used    int64  `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
}

func (x *GetOwnerQuotaResponse) Reset() {
	*x = GetOwnerQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnerQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnerQuotaResponse) ProtoMessage() {}

func (x *GetOwnerQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnerQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetOwnerQuotaResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{3}
}

func (x *GetOwnerQuotaResponse) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *GetOwnerQuotaResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOwnerQuotaResponse) GetUsed() int64 {
	if x != nil {
		return x.Used
	}
	return 0
}

type UpdateQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Size    int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UpdateQuotaRequest) Reset() {
	*x = UpdateQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuotaRequest) ProtoMessage() {}

func (x *UpdateQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuotaRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuotaRequest) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateQuotaRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *UpdateQuotaRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateQuotaResponse) Reset() {
	*x = UpdateQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quota_quota_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuotaResponse) ProtoMessage() {}

func (x *UpdateQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quota_quota_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuotaResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuotaResponse) Descriptor() ([]byte, []int) {
	return file_quota_quota_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_quota_quota_proto protoreflect.FileDescriptor

var file_quota_quota_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x1a, 0x49, 0x73,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x1b, 0x49, 0x73,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x64, 0x22, 0x42, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x84, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x49, 0x73, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12,
	0x21, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x49, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x49, 0x73, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x54, 0x6f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x71, 0x75, 0x6f, 0x74,
	0x61, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x61,
	0x74, 0x65, 0x61, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x3b, 0x71, 0x75,
	0x6f, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quota_quota_proto_rawDescOnce sync.Once
	file_quota_quota_proto_rawDescData = file_quota_quota_proto_rawDesc
)

func file_quota_quota_proto_rawDescGZIP() []byte {
	file_quota_quota_proto_rawDescOnce.Do(func() {
		file_quota_quota_proto_rawDescData = protoimpl.X.CompressGZIP(file_quota_quota_proto_rawDescData)
	})
	return file_quota_quota_proto_rawDescData
}

var file_quota_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quota_quota_proto_goTypes = []interface{}{
	(*IsAllowedToGetQuotaRequest)(nil),  // 0: quota.IsAllowedToGetQuotaRequest
	(*IsAllowedToGetQuotaResponse)(nil), // 1: quota.IsAllowedToGetQuotaResponse
	(*GetOwnerQuotaRequest)(nil),        // 2: quota.GetOwnerQuotaRequest
	(*GetOwnerQuotaResponse)(nil),       // 3: quota.GetOwnerQuotaResponse
	(*UpdateQuotaRequest)(nil),          // 4: quota.UpdateQuotaRequest
	(*UpdateQuotaResponse)(nil),         // 5: quota.UpdateQuotaResponse
}
var file_quota_quota_proto_depIdxs = []int32{
	0, // 0: quota.QuotaService.IsAllowedToGetQuota:input_type -> quota.IsAllowedToGetQuotaRequest
	2, // 1: quota.QuotaService.GetOwnerQuota:input_type -> quota.GetOwnerQuotaRequest
	4, // 2: quota.QuotaService.UpdateQuota:input_type -> quota.UpdateQuotaRequest
	1, // 3: quota.QuotaService.IsAllowedToGetQuota:output_type -> quota.IsAllowedToGetQuotaResponse
	3, // 4: quota.QuotaService.GetOwnerQuota:output_type -> quota.GetOwnerQuotaResponse
	5, // 5: quota.QuotaService.UpdateQuota:output_type -> quota.UpdateQuotaResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quota_quota_proto_init() }
func file_quota_quota_proto_init() {
	if File_quota_quota_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quota_quota_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAllowedToGetQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quota_quota_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAllowedToGetQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quota_quota_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnerQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quota_quota_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnerQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quota_quota_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quota_quota_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quota_quota_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quota_quota_proto_goTypes,
		DependencyIndexes: file_quota_quota_proto_depIdxs,
		MessageInfos:      file_quota_quota_proto_msgTypes,
	}.Build()
	File_quota_quota_proto = out.File
	file_quota_quota_proto_rawDesc = nil
	file_quota_quota_proto_goTypes = nil
	file_quota_quota_proto_depIdxs = nil
}
