// Code generated by protoc-gen-go. DO NOT EDIT.
// source: quota/quota.proto

package quota

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IsAllowedToGetQuotaRequest struct {
	RequestingUser       string   `protobuf:"bytes,1,opt,name=requestingUser,proto3" json:"requestingUser,omitempty"`
	OwnerID              string   `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedToGetQuotaRequest) Reset()         { *m = IsAllowedToGetQuotaRequest{} }
func (m *IsAllowedToGetQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*IsAllowedToGetQuotaRequest) ProtoMessage()    {}
func (*IsAllowedToGetQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{0}
}

func (m *IsAllowedToGetQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedToGetQuotaRequest.Unmarshal(m, b)
}
func (m *IsAllowedToGetQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedToGetQuotaRequest.Marshal(b, m, deterministic)
}
func (m *IsAllowedToGetQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedToGetQuotaRequest.Merge(m, src)
}
func (m *IsAllowedToGetQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_IsAllowedToGetQuotaRequest.Size(m)
}
func (m *IsAllowedToGetQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedToGetQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedToGetQuotaRequest proto.InternalMessageInfo

func (m *IsAllowedToGetQuotaRequest) GetRequestingUser() string {
	if m != nil {
		return m.RequestingUser
	}
	return ""
}

func (m *IsAllowedToGetQuotaRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type IsAllowedToGetQuotaResponse struct {
	Allowed              bool     `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedToGetQuotaResponse) Reset()         { *m = IsAllowedToGetQuotaResponse{} }
func (m *IsAllowedToGetQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*IsAllowedToGetQuotaResponse) ProtoMessage()    {}
func (*IsAllowedToGetQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{1}
}

func (m *IsAllowedToGetQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedToGetQuotaResponse.Unmarshal(m, b)
}
func (m *IsAllowedToGetQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedToGetQuotaResponse.Marshal(b, m, deterministic)
}
func (m *IsAllowedToGetQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedToGetQuotaResponse.Merge(m, src)
}
func (m *IsAllowedToGetQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_IsAllowedToGetQuotaResponse.Size(m)
}
func (m *IsAllowedToGetQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedToGetQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedToGetQuotaResponse proto.InternalMessageInfo

func (m *IsAllowedToGetQuotaResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type GetOwnerQuotaRequest struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerQuotaRequest) Reset()         { *m = GetOwnerQuotaRequest{} }
func (m *GetOwnerQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*GetOwnerQuotaRequest) ProtoMessage()    {}
func (*GetOwnerQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{2}
}

func (m *GetOwnerQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerQuotaRequest.Unmarshal(m, b)
}
func (m *GetOwnerQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerQuotaRequest.Marshal(b, m, deterministic)
}
func (m *GetOwnerQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerQuotaRequest.Merge(m, src)
}
func (m *GetOwnerQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_GetOwnerQuotaRequest.Size(m)
}
func (m *GetOwnerQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerQuotaRequest proto.InternalMessageInfo

func (m *GetOwnerQuotaRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type GetOwnerQuotaResponse struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Used                 int64    `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerQuotaResponse) Reset()         { *m = GetOwnerQuotaResponse{} }
func (m *GetOwnerQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*GetOwnerQuotaResponse) ProtoMessage()    {}
func (*GetOwnerQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{3}
}

func (m *GetOwnerQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerQuotaResponse.Unmarshal(m, b)
}
func (m *GetOwnerQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerQuotaResponse.Marshal(b, m, deterministic)
}
func (m *GetOwnerQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerQuotaResponse.Merge(m, src)
}
func (m *GetOwnerQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_GetOwnerQuotaResponse.Size(m)
}
func (m *GetOwnerQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerQuotaResponse proto.InternalMessageInfo

func (m *GetOwnerQuotaResponse) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *GetOwnerQuotaResponse) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetOwnerQuotaResponse) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type UpdateQuotaRequest struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateQuotaRequest) Reset()         { *m = UpdateQuotaRequest{} }
func (m *UpdateQuotaRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateQuotaRequest) ProtoMessage()    {}
func (*UpdateQuotaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{4}
}

func (m *UpdateQuotaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateQuotaRequest.Unmarshal(m, b)
}
func (m *UpdateQuotaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateQuotaRequest.Marshal(b, m, deterministic)
}
func (m *UpdateQuotaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateQuotaRequest.Merge(m, src)
}
func (m *UpdateQuotaRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateQuotaRequest.Size(m)
}
func (m *UpdateQuotaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateQuotaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateQuotaRequest proto.InternalMessageInfo

func (m *UpdateQuotaRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *UpdateQuotaRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UpdateQuotaResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateQuotaResponse) Reset()         { *m = UpdateQuotaResponse{} }
func (m *UpdateQuotaResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateQuotaResponse) ProtoMessage()    {}
func (*UpdateQuotaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_416bd91ebc5aade8, []int{5}
}

func (m *UpdateQuotaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateQuotaResponse.Unmarshal(m, b)
}
func (m *UpdateQuotaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateQuotaResponse.Marshal(b, m, deterministic)
}
func (m *UpdateQuotaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateQuotaResponse.Merge(m, src)
}
func (m *UpdateQuotaResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateQuotaResponse.Size(m)
}
func (m *UpdateQuotaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateQuotaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateQuotaResponse proto.InternalMessageInfo

func (m *UpdateQuotaResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*IsAllowedToGetQuotaRequest)(nil), "quota.IsAllowedToGetQuotaRequest")
	proto.RegisterType((*IsAllowedToGetQuotaResponse)(nil), "quota.IsAllowedToGetQuotaResponse")
	proto.RegisterType((*GetOwnerQuotaRequest)(nil), "quota.GetOwnerQuotaRequest")
	proto.RegisterType((*GetOwnerQuotaResponse)(nil), "quota.GetOwnerQuotaResponse")
	proto.RegisterType((*UpdateQuotaRequest)(nil), "quota.UpdateQuotaRequest")
	proto.RegisterType((*UpdateQuotaResponse)(nil), "quota.UpdateQuotaResponse")
}

func init() {
	proto.RegisterFile("quota/quota.proto", fileDescriptor_416bd91ebc5aade8)
}

var fileDescriptor_416bd91ebc5aade8 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xb5, 0xad, 0xf5, 0x63, 0xfc, 0x00, 0xa7, 0x15, 0x62, 0xea, 0x41, 0xf7, 0x20, 0x9e, 0x5a,
	0xd1, 0x83, 0x67, 0x45, 0x2c, 0x05, 0x41, 0x8c, 0xf6, 0x24, 0x14, 0x62, 0x32, 0x48, 0x20, 0x66,
	0xd3, 0xec, 0xc6, 0x82, 0x67, 0x7f, 0xb8, 0x64, 0x36, 0xb1, 0x4d, 0x5d, 0xc5, 0x4b, 0x98, 0x37,
	0x1f, 0x6f, 0x5e, 0xde, 0x2c, 0xec, 0x4d, 0x73, 0xa9, 0xfd, 0x01, 0x7f, 0xfb, 0x69, 0x26, 0xb5,
	0xc4, 0x36, 0x03, 0x31, 0x01, 0x77, 0xa4, 0xae, 0xe2, 0x58, 0xce, 0x28, 0x7c, 0x92, 0x43, 0xd2,
	0x0f, 0x45, 0xda, 0xa3, 0x69, 0x4e, 0x4a, 0xe3, 0x09, 0xec, 0x66, 0x26, 0x8c, 0x92, 0xd7, 0xb1,
	0xa2, 0xcc, 0x69, 0x1c, 0x35, 0x4e, 0x37, 0xbd, 0xa5, 0x2c, 0x3a, 0xb0, 0x2e, 0x67, 0x09, 0x65,
	0xa3, 0x1b, 0xa7, 0xc9, 0x0d, 0x15, 0x14, 0x97, 0xd0, 0xb3, 0xf2, 0xab, 0x54, 0x26, 0x8a, 0x8a,
	0x41, 0xdf, 0x14, 0x99, 0x79, 0xc3, 0xab, 0xa0, 0x38, 0x83, 0xee, 0x90, 0xf4, 0x7d, 0x41, 0x53,
	0x93, 0xb4, 0xb0, 0xaa, 0x51, 0x5f, 0xf5, 0x0c, 0xfb, 0x4b, 0x13, 0xf3, 0x25, 0xf6, 0x11, 0xec,
	0x42, 0x3b, 0x8e, 0xde, 0x22, 0xcd, 0xaa, 0x5b, 0x9e, 0x01, 0x88, 0xb0, 0x9a, 0x2b, 0x0a, 0x9d,
	0x16, 0x27, 0x39, 0x16, 0xd7, 0x80, 0xe3, 0x34, 0xf4, 0x35, 0xfd, 0x4f, 0x4c, 0xc1, 0xa1, 0xa2,
	0x0f, 0x2a, 0x89, 0x39, 0x16, 0x03, 0xe8, 0xd4, 0x38, 0xe6, 0xf2, 0x54, 0x1e, 0x04, 0xa4, 0x54,
	0xe5, 0x41, 0x09, 0xcf, 0x3f, 0x9b, 0xb0, 0xcd, 0xbd, 0x8f, 0x94, 0xbd, 0x47, 0x01, 0xe1, 0x04,
	0x3a, 0x16, 0x37, 0xf1, 0xb8, 0x6f, 0x2e, 0xfb, 0xfb, 0x25, 0x5d, 0xf1, 0x57, 0x8b, 0x11, 0x22,
	0x56, 0xf0, 0x0e, 0x76, 0x6a, 0x16, 0x62, 0xaf, 0x1c, 0xb3, 0x9d, 0xc2, 0x3d, 0xb4, 0x17, 0xbf,
	0xd9, 0x6e, 0x61, 0x6b, 0xe1, 0x7f, 0xf1, 0xa0, 0x6c, 0xff, 0xe9, 0xa3, 0xeb, 0xda, 0x4a, 0x15,
	0xcf, 0xcb, 0x1a, 0xbf, 0xd8, 0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x5f, 0x5a, 0xf2,
	0xc6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// QuotaServiceClient is the client API for QuotaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuotaServiceClient interface {
	IsAllowedToGetQuota(ctx context.Context, in *IsAllowedToGetQuotaRequest, opts ...grpc.CallOption) (*IsAllowedToGetQuotaResponse, error)
	GetOwnerQuota(ctx context.Context, in *GetOwnerQuotaRequest, opts ...grpc.CallOption) (*GetOwnerQuotaResponse, error)
	UpdateQuota(ctx context.Context, in *UpdateQuotaRequest, opts ...grpc.CallOption) (*UpdateQuotaResponse, error)
}

type quotaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotaServiceClient(cc grpc.ClientConnInterface) QuotaServiceClient {
	return &quotaServiceClient{cc}
}

func (c *quotaServiceClient) IsAllowedToGetQuota(ctx context.Context, in *IsAllowedToGetQuotaRequest, opts ...grpc.CallOption) (*IsAllowedToGetQuotaResponse, error) {
	out := new(IsAllowedToGetQuotaResponse)
	err := c.cc.Invoke(ctx, "/quota.QuotaService/IsAllowedToGetQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) GetOwnerQuota(ctx context.Context, in *GetOwnerQuotaRequest, opts ...grpc.CallOption) (*GetOwnerQuotaResponse, error) {
	out := new(GetOwnerQuotaResponse)
	err := c.cc.Invoke(ctx, "/quota.QuotaService/GetOwnerQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaServiceClient) UpdateQuota(ctx context.Context, in *UpdateQuotaRequest, opts ...grpc.CallOption) (*UpdateQuotaResponse, error) {
	out := new(UpdateQuotaResponse)
	err := c.cc.Invoke(ctx, "/quota.QuotaService/UpdateQuota", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotaServiceServer is the server API for QuotaService service.
type QuotaServiceServer interface {
	IsAllowedToGetQuota(context.Context, *IsAllowedToGetQuotaRequest) (*IsAllowedToGetQuotaResponse, error)
	GetOwnerQuota(context.Context, *GetOwnerQuotaRequest) (*GetOwnerQuotaResponse, error)
	UpdateQuota(context.Context, *UpdateQuotaRequest) (*UpdateQuotaResponse, error)
}

// UnimplementedQuotaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQuotaServiceServer struct {
}

func (*UnimplementedQuotaServiceServer) IsAllowedToGetQuota(ctx context.Context, req *IsAllowedToGetQuotaRequest) (*IsAllowedToGetQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAllowedToGetQuota not implemented")
}
func (*UnimplementedQuotaServiceServer) GetOwnerQuota(ctx context.Context, req *GetOwnerQuotaRequest) (*GetOwnerQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwnerQuota not implemented")
}
func (*UnimplementedQuotaServiceServer) UpdateQuota(ctx context.Context, req *UpdateQuotaRequest) (*UpdateQuotaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuota not implemented")
}

func RegisterQuotaServiceServer(s *grpc.Server, srv QuotaServiceServer) {
	s.RegisterService(&_QuotaService_serviceDesc, srv)
}

func _QuotaService_IsAllowedToGetQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllowedToGetQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).IsAllowedToGetQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quota.QuotaService/IsAllowedToGetQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).IsAllowedToGetQuota(ctx, req.(*IsAllowedToGetQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_GetOwnerQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOwnerQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).GetOwnerQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quota.QuotaService/GetOwnerQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).GetOwnerQuota(ctx, req.(*GetOwnerQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaService_UpdateQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaServiceServer).UpdateQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quota.QuotaService/UpdateQuota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaServiceServer).UpdateQuota(ctx, req.(*UpdateQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QuotaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quota.QuotaService",
	HandlerType: (*QuotaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAllowedToGetQuota",
			Handler:    _QuotaService_IsAllowedToGetQuota_Handler,
		},
		{
			MethodName: "GetOwnerQuota",
			Handler:    _QuotaService_GetOwnerQuota_Handler,
		},
		{
			MethodName: "UpdateQuota",
			Handler:    _QuotaService_UpdateQuota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quota/quota.proto",
}
