// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUploadRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUploadRequest) Reset()         { *m = CreateUploadRequest{} }
func (m *CreateUploadRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUploadRequest) ProtoMessage()    {}
func (*CreateUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{0}
}
func (m *CreateUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUploadRequest.Unmarshal(m, b)
}
func (m *CreateUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUploadRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadRequest.Merge(dst, src)
}
func (m *CreateUploadRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUploadRequest.Size(m)
}
func (m *CreateUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadRequest proto.InternalMessageInfo

func (m *CreateUploadRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *CreateUploadRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUploadResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUploadResponse) Reset()         { *m = CreateUploadResponse{} }
func (m *CreateUploadResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUploadResponse) ProtoMessage()    {}
func (*CreateUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{1}
}
func (m *CreateUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUploadResponse.Unmarshal(m, b)
}
func (m *CreateUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUploadResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadResponse.Merge(dst, src)
}
func (m *CreateUploadResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUploadResponse.Size(m)
}
func (m *CreateUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadResponse proto.InternalMessageInfo

func (m *CreateUploadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateUploadResponse) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type GenerateKeyRequest struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateKeyRequest) Reset()         { *m = GenerateKeyRequest{} }
func (m *GenerateKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateKeyRequest) ProtoMessage()    {}
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{2}
}
func (m *GenerateKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateKeyRequest.Unmarshal(m, b)
}
func (m *GenerateKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateKeyRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateKeyRequest.Merge(dst, src)
}
func (m *GenerateKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateKeyRequest.Size(m)
}
func (m *GenerateKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateKeyRequest proto.InternalMessageInfo

func (m *GenerateKeyRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type KeyResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyResponse) Reset()         { *m = KeyResponse{} }
func (m *KeyResponse) String() string { return proto.CompactTextString(m) }
func (*KeyResponse) ProtoMessage()    {}
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{3}
}
func (m *KeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyResponse.Unmarshal(m, b)
}
func (m *KeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyResponse.Marshal(b, m, deterministic)
}
func (dst *KeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyResponse.Merge(dst, src)
}
func (m *KeyResponse) XXX_Size() int {
	return xxx_messageInfo_KeyResponse.Size(m)
}
func (m *KeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyResponse proto.InternalMessageInfo

func (m *KeyResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UpdateUploadIDRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	UploadID             string   `protobuf:"bytes,2,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUploadIDRequest) Reset()         { *m = UpdateUploadIDRequest{} }
func (m *UpdateUploadIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUploadIDRequest) ProtoMessage()    {}
func (*UpdateUploadIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{4}
}
func (m *UpdateUploadIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUploadIDRequest.Unmarshal(m, b)
}
func (m *UpdateUploadIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUploadIDRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUploadIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUploadIDRequest.Merge(dst, src)
}
func (m *UpdateUploadIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUploadIDRequest.Size(m)
}
func (m *UpdateUploadIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUploadIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUploadIDRequest proto.InternalMessageInfo

func (m *UpdateUploadIDRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateUploadIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

func (m *UpdateUploadIDRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type UpdateUploadIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUploadIDResponse) Reset()         { *m = UpdateUploadIDResponse{} }
func (m *UpdateUploadIDResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUploadIDResponse) ProtoMessage()    {}
func (*UpdateUploadIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{5}
}
func (m *UpdateUploadIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUploadIDResponse.Unmarshal(m, b)
}
func (m *UpdateUploadIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUploadIDResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUploadIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUploadIDResponse.Merge(dst, src)
}
func (m *UpdateUploadIDResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUploadIDResponse.Size(m)
}
func (m *UpdateUploadIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUploadIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUploadIDResponse proto.InternalMessageInfo

type GetUploadByIDRequest struct {
	UploadID             string   `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadByIDRequest) Reset()         { *m = GetUploadByIDRequest{} }
func (m *GetUploadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUploadByIDRequest) ProtoMessage()    {}
func (*GetUploadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{6}
}
func (m *GetUploadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadByIDRequest.Unmarshal(m, b)
}
func (m *GetUploadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetUploadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadByIDRequest.Merge(dst, src)
}
func (m *GetUploadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUploadByIDRequest.Size(m)
}
func (m *GetUploadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadByIDRequest proto.InternalMessageInfo

func (m *GetUploadByIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

type GetUploadByIDResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	UploadID             string   `protobuf:"bytes,3,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUploadByIDResponse) Reset()         { *m = GetUploadByIDResponse{} }
func (m *GetUploadByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUploadByIDResponse) ProtoMessage()    {}
func (*GetUploadByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{7}
}
func (m *GetUploadByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUploadByIDResponse.Unmarshal(m, b)
}
func (m *GetUploadByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUploadByIDResponse.Marshal(b, m, deterministic)
}
func (dst *GetUploadByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadByIDResponse.Merge(dst, src)
}
func (m *GetUploadByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUploadByIDResponse.Size(m)
}
func (m *GetUploadByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadByIDResponse proto.InternalMessageInfo

func (m *GetUploadByIDResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetUploadByIDResponse) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetUploadByIDResponse) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

func (m *GetUploadByIDResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteUploadByIDRequest struct {
	UploadID             string   `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUploadByIDRequest) Reset()         { *m = DeleteUploadByIDRequest{} }
func (m *DeleteUploadByIDRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUploadByIDRequest) ProtoMessage()    {}
func (*DeleteUploadByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{8}
}
func (m *DeleteUploadByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUploadByIDRequest.Unmarshal(m, b)
}
func (m *DeleteUploadByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUploadByIDRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUploadByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUploadByIDRequest.Merge(dst, src)
}
func (m *DeleteUploadByIDRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUploadByIDRequest.Size(m)
}
func (m *DeleteUploadByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUploadByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUploadByIDRequest proto.InternalMessageInfo

func (m *DeleteUploadByIDRequest) GetUploadID() string {
	if m != nil {
		return m.UploadID
	}
	return ""
}

type DeleteUploadByIDResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUploadByIDResponse) Reset()         { *m = DeleteUploadByIDResponse{} }
func (m *DeleteUploadByIDResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUploadByIDResponse) ProtoMessage()    {}
func (*DeleteUploadByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{9}
}
func (m *DeleteUploadByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUploadByIDResponse.Unmarshal(m, b)
}
func (m *DeleteUploadByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUploadByIDResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUploadByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUploadByIDResponse.Merge(dst, src)
}
func (m *DeleteUploadByIDResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUploadByIDResponse.Size(m)
}
func (m *DeleteUploadByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUploadByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUploadByIDResponse proto.InternalMessageInfo

type GetByFileByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByFileByIDRequest) Reset()         { *m = GetByFileByIDRequest{} }
func (m *GetByFileByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByFileByIDRequest) ProtoMessage()    {}
func (*GetByFileByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{10}
}
func (m *GetByFileByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFileByIDRequest.Unmarshal(m, b)
}
func (m *GetByFileByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFileByIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetByFileByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFileByIDRequest.Merge(dst, src)
}
func (m *GetByFileByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByFileByIDRequest.Size(m)
}
func (m *GetByFileByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFileByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFileByIDRequest proto.InternalMessageInfo

func (m *GetByFileByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetFileByKeyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFileByKeyRequest) Reset()         { *m = GetFileByKeyRequest{} }
func (m *GetFileByKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetFileByKeyRequest) ProtoMessage()    {}
func (*GetFileByKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{11}
}
func (m *GetFileByKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFileByKeyRequest.Unmarshal(m, b)
}
func (m *GetFileByKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFileByKeyRequest.Marshal(b, m, deterministic)
}
func (dst *GetFileByKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFileByKeyRequest.Merge(dst, src)
}
func (m *GetFileByKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetFileByKeyRequest.Size(m)
}
func (m *GetFileByKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFileByKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFileByKeyRequest proto.InternalMessageInfo

func (m *GetFileByKeyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetFilesByFolderRequest struct {
	FolderID             string   `protobuf:"bytes,1,opt,name=folderID,proto3" json:"folderID,omitempty"`
	OwnerID              string   `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesByFolderRequest) Reset()         { *m = GetFilesByFolderRequest{} }
func (m *GetFilesByFolderRequest) String() string { return proto.CompactTextString(m) }
func (*GetFilesByFolderRequest) ProtoMessage()    {}
func (*GetFilesByFolderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{12}
}
func (m *GetFilesByFolderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesByFolderRequest.Unmarshal(m, b)
}
func (m *GetFilesByFolderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesByFolderRequest.Marshal(b, m, deterministic)
}
func (dst *GetFilesByFolderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesByFolderRequest.Merge(dst, src)
}
func (m *GetFilesByFolderRequest) XXX_Size() int {
	return xxx_messageInfo_GetFilesByFolderRequest.Size(m)
}
func (m *GetFilesByFolderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesByFolderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesByFolderRequest proto.InternalMessageInfo

func (m *GetFilesByFolderRequest) GetFolderID() string {
	if m != nil {
		return m.FolderID
	}
	return ""
}

func (m *GetFilesByFolderRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type GetFilesByFolderResponse struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFilesByFolderResponse) Reset()         { *m = GetFilesByFolderResponse{} }
func (m *GetFilesByFolderResponse) String() string { return proto.CompactTextString(m) }
func (*GetFilesByFolderResponse) ProtoMessage()    {}
func (*GetFilesByFolderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{13}
}
func (m *GetFilesByFolderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFilesByFolderResponse.Unmarshal(m, b)
}
func (m *GetFilesByFolderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFilesByFolderResponse.Marshal(b, m, deterministic)
}
func (dst *GetFilesByFolderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFilesByFolderResponse.Merge(dst, src)
}
func (m *GetFilesByFolderResponse) XXX_Size() int {
	return xxx_messageInfo_GetFilesByFolderResponse.Size(m)
}
func (m *GetFilesByFolderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFilesByFolderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFilesByFolderResponse proto.InternalMessageInfo

func (m *GetFilesByFolderResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type CreateFileRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	OwnerID              string   `protobuf:"bytes,5,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Bucket               string   `protobuf:"bytes,6,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Parent               string   `protobuf:"bytes,7,opt,name=parent,proto3" json:"parent,omitempty"`
	AppID                string   `protobuf:"bytes,8,opt,name=appID,proto3" json:"appID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileRequest) Reset()         { *m = CreateFileRequest{} }
func (m *CreateFileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileRequest) ProtoMessage()    {}
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{14}
}
func (m *CreateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFileRequest.Unmarshal(m, b)
}
func (m *CreateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFileRequest.Marshal(b, m, deterministic)
}
func (dst *CreateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileRequest.Merge(dst, src)
}
func (m *CreateFileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFileRequest.Size(m)
}
func (m *CreateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileRequest proto.InternalMessageInfo

func (m *CreateFileRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateFileRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateFileRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateFileRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateFileRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *CreateFileRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *CreateFileRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateFileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

type DeleteFileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileRequest) Reset()         { *m = DeleteFileRequest{} }
func (m *DeleteFileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFileRequest) ProtoMessage()    {}
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{15}
}
func (m *DeleteFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileRequest.Unmarshal(m, b)
}
func (m *DeleteFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileRequest.Merge(dst, src)
}
func (m *DeleteFileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFileRequest.Size(m)
}
func (m *DeleteFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileRequest proto.InternalMessageInfo

func (m *DeleteFileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteFileResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFileResponse) Reset()         { *m = DeleteFileResponse{} }
func (m *DeleteFileResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFileResponse) ProtoMessage()    {}
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{16}
}
func (m *DeleteFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFileResponse.Unmarshal(m, b)
}
func (m *DeleteFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFileResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFileResponse.Merge(dst, src)
}
func (m *DeleteFileResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFileResponse.Size(m)
}
func (m *DeleteFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFileResponse proto.InternalMessageInfo

func (m *DeleteFileResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UpdateFileRequest struct {
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	OwnerID              string   `protobuf:"bytes,5,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Parent               string   `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	AppID                string   `protobuf:"bytes,7,opt,name=appID,proto3" json:"appID,omitempty"`
	Bucket               string   `protobuf:"bytes,11,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFileRequest) Reset()         { *m = UpdateFileRequest{} }
func (m *UpdateFileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateFileRequest) ProtoMessage()    {}
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{17}
}
func (m *UpdateFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFileRequest.Unmarshal(m, b)
}
func (m *UpdateFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFileRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFileRequest.Merge(dst, src)
}
func (m *UpdateFileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateFileRequest.Size(m)
}
func (m *UpdateFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFileRequest proto.InternalMessageInfo

func (m *UpdateFileRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateFileRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UpdateFileRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *UpdateFileRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *UpdateFileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *UpdateFileRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

type IsAllowedRequest struct {
	FileID               string   `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedRequest) Reset()         { *m = IsAllowedRequest{} }
func (m *IsAllowedRequest) String() string { return proto.CompactTextString(m) }
func (*IsAllowedRequest) ProtoMessage()    {}
func (*IsAllowedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{18}
}
func (m *IsAllowedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedRequest.Unmarshal(m, b)
}
func (m *IsAllowedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedRequest.Marshal(b, m, deterministic)
}
func (dst *IsAllowedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedRequest.Merge(dst, src)
}
func (m *IsAllowedRequest) XXX_Size() int {
	return xxx_messageInfo_IsAllowedRequest.Size(m)
}
func (m *IsAllowedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedRequest proto.InternalMessageInfo

func (m *IsAllowedRequest) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *IsAllowedRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type IsAllowedResponse struct {
	Allowed              bool     `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsAllowedResponse) Reset()         { *m = IsAllowedResponse{} }
func (m *IsAllowedResponse) String() string { return proto.CompactTextString(m) }
func (*IsAllowedResponse) ProtoMessage()    {}
func (*IsAllowedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{19}
}
func (m *IsAllowedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsAllowedResponse.Unmarshal(m, b)
}
func (m *IsAllowedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsAllowedResponse.Marshal(b, m, deterministic)
}
func (dst *IsAllowedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsAllowedResponse.Merge(dst, src)
}
func (m *IsAllowedResponse) XXX_Size() int {
	return xxx_messageInfo_IsAllowedResponse.Size(m)
}
func (m *IsAllowedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsAllowedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsAllowedResponse proto.InternalMessageInfo

func (m *IsAllowedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Mail                 string   `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{20}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

type App struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{21}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type File struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	FullName    string `protobuf:"bytes,3,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	OwnerID     string `protobuf:"bytes,6,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	Size        int64  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// Types that are valid to be assigned to FileOrId:
	//	*File_Parent
	//	*File_ParentObject
	FileOrId             isFile_FileOrId `protobuf_oneof:"fileOrId"`
	Bucket               string          `protobuf:"bytes,10,opt,name=bucket,proto3" json:"bucket,omitempty"`
	CreatedAt            int64           `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64           `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_file_46d21ce77198ee12, []int{22}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

type isFile_FileOrId interface {
	isFile_FileOrId()
}

type File_Parent struct {
	Parent string `protobuf:"bytes,8,opt,name=parent,proto3,oneof"`
}
type File_ParentObject struct {
	ParentObject *File `protobuf:"bytes,9,opt,name=parentObject,proto3,oneof"`
}

func (*File_Parent) isFile_FileOrId()       {}
func (*File_ParentObject) isFile_FileOrId() {}

func (m *File) GetFileOrId() isFile_FileOrId {
	if m != nil {
		return m.FileOrId
	}
	return nil
}

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *File) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetParent() string {
	if x, ok := m.GetFileOrId().(*File_Parent); ok {
		return x.Parent
	}
	return ""
}

func (m *File) GetParentObject() *File {
	if x, ok := m.GetFileOrId().(*File_ParentObject); ok {
		return x.ParentObject
	}
	return nil
}

func (m *File) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *File) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *File) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*File) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _File_OneofMarshaler, _File_OneofUnmarshaler, _File_OneofSizer, []interface{}{
		(*File_Parent)(nil),
		(*File_ParentObject)(nil),
	}
}

func _File_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*File)
	// fileOrId
	switch x := m.FileOrId.(type) {
	case *File_Parent:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Parent)
	case *File_ParentObject:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ParentObject); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("File.FileOrId has unexpected type %T", x)
	}
	return nil
}

func _File_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*File)
	switch tag {
	case 8: // fileOrId.parent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.FileOrId = &File_Parent{x}
		return true, err
	case 9: // fileOrId.parentObject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(File)
		err := b.DecodeMessage(msg)
		m.FileOrId = &File_ParentObject{msg}
		return true, err
	default:
		return false, nil
	}
}

func _File_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*File)
	// fileOrId
	switch x := m.FileOrId.(type) {
	case *File_Parent:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Parent)))
		n += len(x.Parent)
	case *File_ParentObject:
		s := proto.Size(x.ParentObject)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*CreateUploadRequest)(nil), "file.CreateUploadRequest")
	proto.RegisterType((*CreateUploadResponse)(nil), "file.CreateUploadResponse")
	proto.RegisterType((*GenerateKeyRequest)(nil), "file.GenerateKeyRequest")
	proto.RegisterType((*KeyResponse)(nil), "file.KeyResponse")
	proto.RegisterType((*UpdateUploadIDRequest)(nil), "file.UpdateUploadIDRequest")
	proto.RegisterType((*UpdateUploadIDResponse)(nil), "file.UpdateUploadIDResponse")
	proto.RegisterType((*GetUploadByIDRequest)(nil), "file.GetUploadByIDRequest")
	proto.RegisterType((*GetUploadByIDResponse)(nil), "file.GetUploadByIDResponse")
	proto.RegisterType((*DeleteUploadByIDRequest)(nil), "file.DeleteUploadByIDRequest")
	proto.RegisterType((*DeleteUploadByIDResponse)(nil), "file.DeleteUploadByIDResponse")
	proto.RegisterType((*GetByFileByIDRequest)(nil), "file.GetByFileByIDRequest")
	proto.RegisterType((*GetFileByKeyRequest)(nil), "file.GetFileByKeyRequest")
	proto.RegisterType((*GetFilesByFolderRequest)(nil), "file.GetFilesByFolderRequest")
	proto.RegisterType((*GetFilesByFolderResponse)(nil), "file.GetFilesByFolderResponse")
	proto.RegisterType((*CreateFileRequest)(nil), "file.CreateFileRequest")
	proto.RegisterType((*DeleteFileRequest)(nil), "file.DeleteFileRequest")
	proto.RegisterType((*DeleteFileResponse)(nil), "file.DeleteFileResponse")
	proto.RegisterType((*UpdateFileRequest)(nil), "file.UpdateFileRequest")
	proto.RegisterType((*IsAllowedRequest)(nil), "file.IsAllowedRequest")
	proto.RegisterType((*IsAllowedResponse)(nil), "file.IsAllowedResponse")
	proto.RegisterType((*User)(nil), "file.User")
	proto.RegisterType((*App)(nil), "file.App")
	proto.RegisterType((*File)(nil), "file.File")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileServiceClient interface {
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error)
	CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error)
	UpdateUploadID(ctx context.Context, in *UpdateUploadIDRequest, opts ...grpc.CallOption) (*UpdateUploadIDResponse, error)
	GetUploadByID(ctx context.Context, in *GetUploadByIDRequest, opts ...grpc.CallOption) (*GetUploadByIDResponse, error)
	DeleteUploadByID(ctx context.Context, in *DeleteUploadByIDRequest, opts ...grpc.CallOption) (*DeleteUploadByIDResponse, error)
	GetFileByID(ctx context.Context, in *GetByFileByIDRequest, opts ...grpc.CallOption) (*File, error)
	GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (*File, error)
	GetFilesByFolder(ctx context.Context, in *GetFilesByFolderRequest, opts ...grpc.CallOption) (*GetFilesByFolderResponse, error)
	CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*File, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*File, error)
	IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error)
}

type fileServiceClient struct {
	cc *grpc.ClientConn
}

func NewFileServiceClient(cc *grpc.ClientConn) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GenerateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error) {
	out := new(CreateUploadResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/CreateUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateUploadID(ctx context.Context, in *UpdateUploadIDRequest, opts ...grpc.CallOption) (*UpdateUploadIDResponse, error) {
	out := new(UpdateUploadIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/UpdateUploadID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetUploadByID(ctx context.Context, in *GetUploadByIDRequest, opts ...grpc.CallOption) (*GetUploadByIDResponse, error) {
	out := new(GetUploadByIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetUploadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteUploadByID(ctx context.Context, in *DeleteUploadByIDRequest, opts ...grpc.CallOption) (*DeleteUploadByIDResponse, error) {
	out := new(DeleteUploadByIDResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/DeleteUploadByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileByID(ctx context.Context, in *GetByFileByIDRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFileByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFileByKey(ctx context.Context, in *GetFileByKeyRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFileByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) GetFilesByFolder(ctx context.Context, in *GetFilesByFolderRequest, opts ...grpc.CallOption) (*GetFilesByFolderResponse, error) {
	out := new(GetFilesByFolderResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/GetFilesByFolder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) CreateFile(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/CreateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/DeleteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) UpdateFile(ctx context.Context, in *UpdateFileRequest, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/file.FileService/UpdateFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) IsAllowed(ctx context.Context, in *IsAllowedRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error) {
	out := new(IsAllowedResponse)
	err := c.cc.Invoke(ctx, "/file.FileService/IsAllowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
type FileServiceServer interface {
	GenerateKey(context.Context, *GenerateKeyRequest) (*KeyResponse, error)
	CreateUpload(context.Context, *CreateUploadRequest) (*CreateUploadResponse, error)
	UpdateUploadID(context.Context, *UpdateUploadIDRequest) (*UpdateUploadIDResponse, error)
	GetUploadByID(context.Context, *GetUploadByIDRequest) (*GetUploadByIDResponse, error)
	DeleteUploadByID(context.Context, *DeleteUploadByIDRequest) (*DeleteUploadByIDResponse, error)
	GetFileByID(context.Context, *GetByFileByIDRequest) (*File, error)
	GetFileByKey(context.Context, *GetFileByKeyRequest) (*File, error)
	GetFilesByFolder(context.Context, *GetFilesByFolderRequest) (*GetFilesByFolderResponse, error)
	CreateFile(context.Context, *CreateFileRequest) (*File, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	UpdateFile(context.Context, *UpdateFileRequest) (*File, error)
	IsAllowed(context.Context, *IsAllowedRequest) (*IsAllowedResponse, error)
}

func RegisterFileServiceServer(s *grpc.Server, srv FileServiceServer) {
	s.RegisterService(&_FileService_serviceDesc, srv)
}

func _FileService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GenerateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/CreateUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateUpload(ctx, req.(*CreateUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateUploadID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUploadIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateUploadID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/UpdateUploadID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateUploadID(ctx, req.(*UpdateUploadIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetUploadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetUploadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetUploadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetUploadByID(ctx, req.(*GetUploadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteUploadByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUploadByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteUploadByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/DeleteUploadByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteUploadByID(ctx, req.(*DeleteUploadByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByFileByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFileByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileByID(ctx, req.(*GetByFileByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFileByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFileByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFileByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFileByKey(ctx, req.(*GetFileByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_GetFilesByFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesByFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetFilesByFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/GetFilesByFolder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetFilesByFolder(ctx, req.(*GetFilesByFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_CreateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).CreateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/CreateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).CreateFile(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_UpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).UpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/UpdateFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).UpdateFile(ctx, req.(*UpdateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_IsAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAllowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).IsAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/file.FileService/IsAllowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).IsAllowed(ctx, req.(*IsAllowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "file.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _FileService_GenerateKey_Handler,
		},
		{
			MethodName: "CreateUpload",
			Handler:    _FileService_CreateUpload_Handler,
		},
		{
			MethodName: "UpdateUploadID",
			Handler:    _FileService_UpdateUploadID_Handler,
		},
		{
			MethodName: "GetUploadByID",
			Handler:    _FileService_GetUploadByID_Handler,
		},
		{
			MethodName: "DeleteUploadByID",
			Handler:    _FileService_DeleteUploadByID_Handler,
		},
		{
			MethodName: "GetFileByID",
			Handler:    _FileService_GetFileByID_Handler,
		},
		{
			MethodName: "GetFileByKey",
			Handler:    _FileService_GetFileByKey_Handler,
		},
		{
			MethodName: "GetFilesByFolder",
			Handler:    _FileService_GetFilesByFolder_Handler,
		},
		{
			MethodName: "CreateFile",
			Handler:    _FileService_CreateFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _FileService_DeleteFile_Handler,
		},
		{
			MethodName: "UpdateFile",
			Handler:    _FileService_UpdateFile_Handler,
		},
		{
			MethodName: "IsAllowed",
			Handler:    _FileService_IsAllowed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file.proto",
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_file_46d21ce77198ee12) }

var fileDescriptor_file_46d21ce77198ee12 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x4e, 0xe3, 0x46,
	0x18, 0x26, 0x71, 0x48, 0xc8, 0x9f, 0x14, 0x91, 0xe1, 0x10, 0xd7, 0xd0, 0x16, 0x4d, 0xab, 0x96,
	0x4a, 0x2d, 0xaa, 0x40, 0x55, 0x6f, 0x50, 0xd5, 0xa4, 0xa8, 0x94, 0x56, 0xbb, 0x48, 0x41, 0x5c,
	0xee, 0x85, 0x89, 0x27, 0x92, 0x17, 0x13, 0x1b, 0xdb, 0x59, 0x94, 0x7d, 0x9d, 0x7d, 0x89, 0x7d,
	0x85, 0xbd, 0xdf, 0x07, 0xda, 0x39, 0xda, 0xbf, 0x0f, 0x61, 0x97, 0xbb, 0xf9, 0x0f, 0xfe, 0xfe,
	0xe3, 0xcc, 0x67, 0x80, 0x99, 0x1f, 0xb0, 0xe3, 0x28, 0x0e, 0xd3, 0x90, 0xb4, 0xc4, 0x99, 0x8e,
	0x60, 0xfb, 0xef, 0x98, 0xb9, 0x29, 0xbb, 0x89, 0x82, 0xd0, 0xf5, 0x26, 0xec, 0x61, 0xc1, 0x92,
	0x94, 0xec, 0x41, 0xfb, 0x76, 0x31, 0xbd, 0x63, 0xa9, 0xdd, 0x38, 0x6c, 0x1c, 0x75, 0x27, 0x5a,
	0x22, 0x04, 0x5a, 0x73, 0xf7, 0x9e, 0xd9, 0x4d, 0xa9, 0x95, 0x67, 0xfa, 0x17, 0xec, 0x14, 0x21,
	0x92, 0x28, 0x9c, 0x27, 0x8c, 0x6c, 0x81, 0x75, 0xc7, 0x96, 0x1a, 0x40, 0x1c, 0x11, 0x6a, 0x13,
	0xa3, 0xd2, 0x5f, 0x80, 0x5c, 0xb0, 0x39, 0x8b, 0x39, 0xc6, 0xff, 0x6c, 0xf9, 0x99, 0x1c, 0xe8,
	0x77, 0xd0, 0x93, 0x5e, 0xab, 0xc2, 0xd0, 0x57, 0xb0, 0x7b, 0x13, 0x79, 0x59, 0x42, 0x97, 0xe7,
	0x06, 0xb1, 0x9a, 0x91, 0x03, 0x1b, 0x0b, 0xed, 0xa4, 0x73, 0xca, 0x64, 0x14, 0xdf, 0x2a, 0xc4,
	0xb7, 0x61, 0xaf, 0x0c, 0xaf, 0x52, 0xa1, 0x27, 0xb0, 0x73, 0xc1, 0x52, 0xa5, 0x1e, 0x2f, 0xf3,
	0xb8, 0x38, 0x4a, 0xa3, 0x18, 0x85, 0x3e, 0xc0, 0x6e, 0xe9, 0x9b, 0xe7, 0xb6, 0xaf, 0x00, 0x6f,
	0x95, 0x8a, 0x30, 0x03, 0x6b, 0xa1, 0x81, 0xfd, 0x0e, 0xc3, 0x73, 0x16, 0x30, 0x53, 0xc0, 0x97,
	0x66, 0xea, 0x80, 0x5d, 0xfd, 0x4c, 0x57, 0xfe, 0xa3, 0xac, 0x7c, 0xbc, 0xfc, 0x87, 0xef, 0x14,
	0xc6, 0xdb, 0x84, 0xa6, 0xef, 0x69, 0x24, 0x7e, 0xa2, 0x3f, 0xc1, 0x36, 0xf7, 0x53, 0x5e, 0x68,
	0xd4, 0xd5, 0x19, 0x5e, 0xc1, 0x50, 0x3b, 0x26, 0x1c, 0x35, 0x0c, 0x3c, 0x16, 0xa3, 0x1c, 0x67,
	0x52, 0x91, 0xe7, 0x68, 0x64, 0x62, 0x43, 0x27, 0x7c, 0x9c, 0x4b, 0x93, 0xea, 0x91, 0x11, 0xe9,
	0x19, 0xd8, 0x55, 0x40, 0xdd, 0xea, 0x43, 0x58, 0x17, 0x97, 0x21, 0xe1, 0x70, 0xd6, 0x51, 0xef,
	0x04, 0x8e, 0xe5, 0x35, 0x11, 0xbe, 0x13, 0x65, 0xa0, 0x1f, 0x1a, 0x30, 0x50, 0x4b, 0x2e, 0xb5,
	0x4f, 0xed, 0xd3, 0x6c, 0x11, 0x04, 0x2f, 0xf3, 0x3b, 0x92, 0xc9, 0x62, 0x14, 0x89, 0xff, 0x96,
	0xc9, 0x11, 0x59, 0x13, 0x79, 0x16, 0xba, 0x74, 0x19, 0x65, 0xe3, 0x11, 0x67, 0x5c, 0xc3, 0x7a,
	0xa1, 0x06, 0xb4, 0x00, 0xed, 0xc2, 0x02, 0x70, 0x7d, 0xe4, 0xc6, 0x6c, 0x9e, 0xda, 0x1d, 0xa5,
	0x57, 0x12, 0xd9, 0x81, 0x75, 0x37, 0x8a, 0x38, 0xce, 0x86, 0x54, 0x2b, 0x81, 0x7e, 0x0f, 0x03,
	0x35, 0x47, 0x5c, 0x4a, 0x79, 0x50, 0x3f, 0x00, 0xc1, 0x4e, 0xba, 0x51, 0xdc, 0x2b, 0xbc, 0x93,
	0x5e, 0x1b, 0x13, 0x7e, 0xa2, 0xef, 0x78, 0x5b, 0xd4, 0x5d, 0xc0, 0x58, 0xcf, 0x6d, 0xc2, 0x93,
	0x05, 0xeb, 0xc2, 0xda, 0xf5, 0x85, 0x75, 0x50, 0x61, 0xa8, 0x3d, 0xbd, 0xc2, 0x85, 0x1d, 0xc3,
	0xd6, 0x65, 0x32, 0x0a, 0x82, 0xf0, 0x91, 0xe1, 0x07, 0x4e, 0x4c, 0x36, 0x5b, 0x21, 0x2d, 0x09,
	0xfd, 0x22, 0x41, 0xfb, 0xa3, 0x25, 0xfa, 0x2b, 0x0c, 0x10, 0x86, 0x6e, 0x07, 0x4f, 0xdc, 0x55,
	0x2a, 0xdd, 0x13, 0x23, 0x52, 0x0f, 0x5a, 0x37, 0xfc, 0xc3, 0x72, 0x5b, 0xc9, 0x01, 0x74, 0x67,
	0x7e, 0x9c, 0xa4, 0xa8, 0x37, 0xb9, 0x42, 0x34, 0x2e, 0x70, 0xb5, 0x51, 0x5f, 0x64, 0x23, 0x8b,
	0xc6, 0xdd, 0xbb, 0x7e, 0x60, 0x36, 0x45, 0x9c, 0xe9, 0xcf, 0x60, 0x8d, 0xa2, 0xa8, 0x12, 0xa4,
	0xee, 0x91, 0xfe, 0xd8, 0x84, 0x96, 0x98, 0x51, 0xc5, 0x59, 0xef, 0x70, 0xb3, 0x7e, 0x87, 0xad,
	0xea, 0xf8, 0x2a, 0xfb, 0x7a, 0x08, 0x3d, 0x8f, 0x25, 0xd3, 0xd8, 0x8f, 0x52, 0x3f, 0x9c, 0xeb,
	0x11, 0x62, 0x15, 0x1e, 0x70, 0xbb, 0x38, 0x60, 0xb3, 0x0e, 0x9d, 0xc2, 0x3a, 0x98, 0xa1, 0xcb,
	0xb5, 0xfd, 0x77, 0x2d, 0x1b, 0xfb, 0x6f, 0xd0, 0x57, 0xa7, 0xab, 0xdb, 0xd7, 0x6c, 0x9a, 0xda,
	0x5d, 0x6e, 0x2f, 0x5c, 0x57, 0xee, 0x5b, 0xf0, 0x40, 0x2b, 0x01, 0x85, 0x1b, 0xc3, 0xe7, 0x30,
	0x95, 0xd7, 0xd9, 0x1b, 0xa9, 0x6d, 0xb1, 0x26, 0xb9, 0x42, 0x58, 0x17, 0x72, 0xab, 0x85, 0xb5,
	0xaf, 0xac, 0x99, 0x62, 0x0c, 0xbc, 0x3f, 0x3c, 0xd6, 0x55, 0x7c, 0xe9, 0x9d, 0xbc, 0x6f, 0x43,
	0x4f, 0x04, 0xbe, 0x66, 0xf1, 0x1b, 0x7f, 0xca, 0xc8, 0x19, 0xf4, 0x10, 0x93, 0x11, 0x5b, 0xa5,
	0x56, 0x25, 0x37, 0x67, 0xa0, 0x2c, 0x88, 0xc8, 0xe8, 0x1a, 0xb9, 0x80, 0x3e, 0x66, 0x52, 0xf2,
	0xb5, 0x72, 0xaa, 0x21, 0x68, 0xc7, 0xa9, 0x33, 0x65, 0x40, 0x2f, 0x60, 0xb3, 0x48, 0x51, 0x64,
	0x5f, 0xf9, 0xd7, 0xf2, 0xa2, 0x73, 0x50, 0x6f, 0xcc, 0xe0, 0xfe, 0x83, 0xaf, 0x0a, 0x1c, 0x45,
	0x1c, 0x53, 0x57, 0x95, 0xec, 0x9c, 0xfd, 0x5a, 0x5b, 0x86, 0x75, 0x0d, 0x5b, 0x65, 0x16, 0x21,
	0xdf, 0xa8, 0x4f, 0x56, 0x90, 0x92, 0xf3, 0xed, 0x2a, 0x73, 0x06, 0xfa, 0x87, 0x68, 0x7b, 0x6a,
	0xc8, 0x07, 0xa5, 0x57, 0x61, 0x24, 0x07, 0x6d, 0x8b, 0xfc, 0xb0, 0x8f, 0xf9, 0xc8, 0x74, 0xbc,
	0x86, 0xa3, 0x4a, 0x1f, 0xf2, 0x32, 0xca, 0x74, 0x62, 0xca, 0x58, 0xc1, 0x5b, 0xa6, 0x8c, 0x55,
	0x2c, 0xc4, 0x41, 0x4f, 0x01, 0x72, 0x92, 0x21, 0x43, 0x3c, 0x62, 0xf4, 0xbe, 0x96, 0x32, 0x19,
	0x01, 0xe4, 0x2f, 0xb5, 0xf9, 0xa8, 0xf2, 0xc0, 0x3b, 0x76, 0xd5, 0x80, 0xe3, 0xe6, 0xaf, 0xb8,
	0x81, 0xa8, 0xbc, 0xeb, 0xa5, 0xb8, 0x7f, 0x42, 0x37, 0x7b, 0x11, 0xc9, 0x9e, 0x32, 0x95, 0x9f,
	0x59, 0x67, 0x58, 0xd1, 0x9b, 0xa0, 0xb7, 0x6d, 0xf9, 0x1b, 0x7a, 0xfa, 0x29, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x1c, 0xad, 0xb5, 0x94, 0x0a, 0x00, 0x00,
}
